"""Preservation contracts for user-facing documents generated by PLAGENOR 4.0.

These contracts list source-model elements that may be restyled but must not
silently disappear from generated outputs.
"""

FINANCIAL_SOURCE_FIELDS = (
    "Date", "N°", "Client", "Tél :", "Fax :",
    "Prestation", "Quantité", "Prix unitaire DA", "Montant DA",
    "Siège social", "Coordonnées", "Cpte CCP Agent comptable",
)

FINANCIAL_SOURCE_VALUES = (
    "École Supérieure en Sciences Biologiques d'Oran",
    "BP 1042 SAIM MOHAMED",
    "Cité Emir Abdelkader (EX-INESSMO)",
    "31000 Oran",
    "00831001131000208471",
    "415020000310784",
    "007999990000324044 14",
    "+213 41 24 63 59",
    "https://essb-oran.edu.dz/",
)

PLATFORM_NOTE_FIELDS = (
    "Référence", "Date d'émission", "Nom complet", "Établissement",
    "Laboratoire", "Niveau / fonction", "Directeur de recherche",
    "Email", "Téléphone", "Code", "Intitulé", "Description",
    "Délai (jours ouvrables)", "Canal", "Urgence", "Titre",
    "Échantillons", "Budget annuel par étudiant",
    "Montant de cette prestation", "Solde IBTIKAR déclaré",
    "Analyste", "Email analyste", "Rendez-vous",
)

RECEPTION_FIELDS = (
    "Service", "Canal", "Urgence", "Date de RDV", "Analyste assigné",
    "Date de soumission", "Nom", "Email", "Téléphone", "Établissement",
    "Laboratoire", "Tableau des échantillons", "Date de réception",
    "Nombre d'échantillons reçus", "État des échantillons", "Observations",
    "Signature du réceptionniste", "Signature du déposant",
)

STATS_FIELDS = (
    "Statistiques institutionnelles", "Indicateurs principaux",
    "Demandes", "Complétées", "En cours", "Rejetées",
    "Taux de complétion", "Demandes IBTIKAR", "Demandes GENOCLAB",
    "Revenu virtuel IBTIKAR", "Revenu GENOCLAB",
    "Répartition par service", "Répartition par statut",
    "Répartition par wilaya", "Répartition par établissement",
    "Répartition par cadre d'analyse", "Répartition par sexe",
    "Tendance mensuelle",
)

IBTIKAR_CONTROL_FIELDS = (
    "Numéro de demande", "Date de la demande", "Version du formulaire source",
    "Révision numérique", "Code", "Référence IBTIKAR-DGRSDT",
    "Nombre de lignes enregistrées",
)

IBTIKAR_VALIDATION_FIELDS = (
    "Cadre réservé à PLAGENOR", "Signature de l’opérateur",
    "Visa du Chef du Service Commun", "Visa du Directeur de l’ESSBO",
)
