# Generated by Django 5.1 on 2026-03-28 01:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('channel_availability', models.CharField(choices=[('BOTH', 'IBTIKAR & GENOCLAB'), ('IBTIKAR', 'IBTIKAR uniquement'), ('GENOCLAB', 'GENOCLAB uniquement')], default='BOTH', max_length=10)),
                ('service_type', models.CharField(default='Analysis', max_length=50)),
                ('ibtikar_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('genoclab_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('turnaround_days', models.IntegerField(default=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PlatformContent',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField(default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_content',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('channel', models.CharField(choices=[('IBTIKAR', 'IBTIKAR'), ('GENOCLAB', 'GENOCLAB')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('VALIDATION_PEDAGOGIQUE', 'Validation Pédagogique'), ('VALIDATION_FINANCE', 'Validation Finance'), ('PLATFORM_NOTE_GENERATED', 'Note Générée'), ('ASSIGNED', 'Assigné'), ('PENDING_ACCEPTANCE', 'En Attente Acceptation'), ('APPOINTMENT_SCHEDULED', 'RDV Planifié'), ('SAMPLE_RECEIVED', 'Échantillon Reçu'), ('ANALYSIS_STARTED', 'Analyse Démarrée'), ('ANALYSIS_FINISHED', 'Analyse Terminée'), ('REPORT_UPLOADED', 'Rapport Uploadé'), ('ADMIN_REVIEW', 'Révision Admin'), ('REPORT_VALIDATED', 'Rapport Validé'), ('SENT_TO_REQUESTER', 'Transmis Demandeur'), ('COMPLETED', 'Complété'), ('CLOSED', 'Clôturé'), ('REJECTED', 'Rejeté'), ('REQUEST_CREATED', 'Demande Créée'), ('QUOTE_DRAFT', 'Devis En Cours'), ('QUOTE_SENT', 'Devis Envoyé'), ('QUOTE_VALIDATED_BY_CLIENT', 'Devis Accepté'), ('QUOTE_REJECTED_BY_CLIENT', 'Devis Refusé'), ('INVOICE_GENERATED', 'Facture Émise'), ('PAYMENT_CONFIRMED', 'Paiement Confirmé'), ('SENT_TO_CLIENT', 'Transmis Client'), ('ARCHIVED', 'Archivé')], default='SUBMITTED', max_length=30)),
                ('urgency', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Très urgent', 'Très urgent')], default='Normal', max_length=20)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('declared_ibtikar_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quote_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('admin_validated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_confirmed', models.BooleanField(default=False)),
                ('appointment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_accepted', models.BooleanField(default=False)),
                ('assignment_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_declined', models.BooleanField(default=False)),
                ('assignment_decline_reason', models.TextField(blank=True, default='')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('report_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('report_delivered', models.BooleanField(default=False)),
                ('report_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('admin_revision_notes', models.TextField(blank=True, default='')),
                ('service_rating', models.IntegerField(blank=True, null=True)),
                ('rating_comment', models.TextField(blank=True, default='')),
                ('rated_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_confirmed', models.BooleanField(default=False)),
                ('receipt_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_as_guest', models.BooleanField(default=False)),
                ('guest_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('guest_name', models.CharField(blank=True, default='', max_length=200)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254)),
                ('guest_phone', models.CharField(blank=True, default='', max_length=50)),
                ('service_params', models.JSONField(blank=True, default=dict)),
                ('pricing', models.JSONField(blank=True, default=dict)),
                ('sample_table', models.JSONField(blank=True, default=list)),
                ('requester_data', models.JSONField(blank=True, default=dict)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='accounts.memberprofile')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
            ],
            options={
                'db_table': 'requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('line_items', models.JSONField(default=list)),
                ('subtotal_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.19, max_digits=4)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.request')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('step', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.request')),
            ],
            options={
                'db_table': 'request_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('forced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.request')),
            ],
            options={
                'db_table': 'request_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['channel', 'status'], name='requests_channel_60f8ae_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['channel', 'archived'], name='requests_channel_410b98_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status'], name='requests_status_58d546_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['requester'], name='requests_request_5bf436_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['assigned_to', 'status'], name='requests_assigne_815d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['guest_token'], name='requests_guest_t_099ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['report_token'], name='requests_report__c19a8c_idx'),
        ),
    ]
