# Generated by Django 5.1 on 2026-03-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_revenuearchive_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PARTIAL', 'Partiel'), ('COMPLETED', 'Payé')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('VALIDATION_PEDAGOGIQUE', 'Validation Pédagogique'), ('VALIDATION_FINANCE', 'Validation Finance'), ('PLATFORM_NOTE_GENERATED', 'Note Générée'), ('ASSIGNED', 'Assigné'), ('PENDING_ACCEPTANCE', 'En Attente Acceptation'), ('APPOINTMENT_PROPOSED', 'RDV Proposé'), ('APPOINTMENT_CONFIRMED', 'RDV Confirmé'), ('SAMPLE_RECEIVED', 'Échantillon Reçu'), ('ANALYSIS_STARTED', 'Analyse Démarrée'), ('ANALYSIS_FINISHED', 'Analyse Terminée'), ('REPORT_UPLOADED', 'Rapport Uploadé'), ('ADMIN_REVIEW', 'Révision Admin'), ('REPORT_VALIDATED', 'Rapport Validé'), ('SENT_TO_REQUESTER', 'Transmis Demandeur'), ('COMPLETED', 'Complété'), ('CLOSED', 'Clôturé'), ('REJECTED', 'Rejeté'), ('REQUEST_CREATED', 'Demande Créée'), ('QUOTE_DRAFT', 'Devis En Cours'), ('QUOTE_SENT', 'Devis Envoyé'), ('QUOTE_VALIDATED_BY_CLIENT', 'Devis Accepté'), ('QUOTE_REJECTED_BY_CLIENT', 'Devis Refusé'), ('INVOICE_GENERATED', 'Facture Émise'), ('PAYMENT_CONFIRMED', 'Paiement Confirmé'), ('SENT_TO_CLIENT', 'Transmis Client'), ('ARCHIVED', 'Archivé')], default='SUBMITTED', max_length=30),
        ),
        migrations.CreateModel(
            name='ServiceFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('string', 'Texte'), ('enum', 'Liste'), ('boolean', 'Oui/Non'), ('number', 'Nombre')], default='string', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for enum type')),
                ('required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='core.service')),
            ],
            options={
                'db_table': 'service_form_fields',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
