# Generated by Django 5.1 on 2026-03-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoice_payment_status_alter_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='quote_detail',
            field=models.JSONField(blank=True, default=dict, verbose_name='Détail du devis'),
        ),
    ]
