# Generated by Django 5.1 on 2026-03-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quote_detail_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='alt_date_note',
            field=models.TextField(blank=True, default='', verbose_name='Note date alternative'),
        ),
        migrations.AddField(
            model_name='request',
            name='alt_date_proposed',
            field=models.DateField(blank=True, null=True, verbose_name='Date alternative proposée'),
        ),
    ]
