# Generated by Django 5.1 on 2026-03-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alt_date_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='ibtikar_external_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Code demande IBTIKAR-DGRSDT'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('VALIDATION_PEDAGOGIQUE', 'Validation Pédagogique'), ('VALIDATION_FINANCE', 'Validation Finance'), ('PLATFORM_NOTE_GENERATED', 'Note Générée'), ('IBTIKAR_SUBMISSION_PENDING', 'En attente soumission IBTIKAR'), ('IBTIKAR_CODE_SUBMITTED', 'Code IBTIKAR soumis'), ('ASSIGNED', 'Assigné'), ('PENDING_ACCEPTANCE', 'En Attente Acceptation'), ('APPOINTMENT_PROPOSED', 'RDV Proposé'), ('APPOINTMENT_CONFIRMED', 'RDV Confirmé'), ('SAMPLE_RECEIVED', 'Échantillon Reçu'), ('ANALYSIS_STARTED', 'Analyse Démarrée'), ('ANALYSIS_FINISHED', 'Analyse Terminée'), ('REPORT_UPLOADED', 'Rapport Uploadé'), ('ADMIN_REVIEW', 'Révision Admin'), ('REPORT_VALIDATED', 'Rapport Validé'), ('SENT_TO_REQUESTER', 'Transmis Demandeur'), ('COMPLETED', 'Complété'), ('CLOSED', 'Clôturé'), ('REJECTED', 'Rejeté'), ('REQUEST_CREATED', 'Demande Créée'), ('QUOTE_DRAFT', 'Devis En Cours'), ('QUOTE_SENT', 'Devis Envoyé'), ('QUOTE_VALIDATED_BY_CLIENT', 'Devis Accepté'), ('QUOTE_REJECTED_BY_CLIENT', 'Devis Refusé'), ('INVOICE_GENERATED', 'Facture Émise'), ('PAYMENT_CONFIRMED', 'Paiement Confirmé'), ('SENT_TO_CLIENT', 'Transmis Client'), ('ARCHIVED', 'Archivé')], default='SUBMITTED', max_length=30),
        ),
    ]
