# Generated by Django 5.1.7 on 2026-03-29 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ibtikar_workflow_states'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(choices=[('BASE', 'Prix de base'), ('PER_SAMPLE', 'Par échantillon'), ('PER_PARAMETER', 'Par paramètre'), ('URGENCY_SURCHARGE', 'Majoration urgence'), ('DISCOUNT', 'Remise')], default='BASE', max_length=20)),
                ('channel', models.CharField(choices=[('IBTIKAR', 'IBTIKAR'), ('GENOCLAB', 'GENOCLAB'), ('BOTH', 'Les deux')], default='BOTH', max_length=10)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du tarif')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant (DZD)')),
                ('unit', models.CharField(blank=True, default='固定', max_length=50, verbose_name='Unité (ex: par échantillon)')),
                ('min_quantity', models.IntegerField(default=1, verbose_name='Quantité minimum')),
                ('max_quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantité maximum')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant minimum')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant maximum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('priority', models.IntegerField(default=0, verbose_name='Priorité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_configs', to='core.service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration tarifaire',
                'verbose_name_plural': 'Configurations tarifaires',
                'db_table': 'service_pricing',
                'ordering': ['service', 'priority', 'pk'],
            },
        ),
    ]
