# Generated by Django 5.1.7 on 2026-03-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_service_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='order_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/', verbose_name='Bon de commande'),
        ),
        migrations.AddField(
            model_name='request',
            name='order_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='payments/', verbose_name='Reçu de paiement'),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('VALIDATION_PEDAGOGIQUE', 'Validation Pédagogique'), ('VALIDATION_FINANCE', 'Validation Finance'), ('PLATFORM_NOTE_GENERATED', 'Note Générée'), ('IBTIKAR_SUBMISSION_PENDING', 'En attente soumission IBTIKAR'), ('IBTIKAR_CODE_SUBMITTED', 'Code IBTIKAR soumis'), ('ASSIGNED', 'Assigné'), ('PENDING_ACCEPTANCE', 'En Attente Acceptation'), ('APPOINTMENT_PROPOSED', 'RDV Proposé'), ('APPOINTMENT_CONFIRMED', 'RDV Confirmé'), ('SAMPLE_RECEIVED', 'Échantillon Reçu'), ('ANALYSIS_STARTED', 'Analyse Démarrée'), ('ANALYSIS_FINISHED', 'Analyse Terminée'), ('REPORT_UPLOADED', 'Rapport Uploadé'), ('ADMIN_REVIEW', 'Révision Admin'), ('REPORT_VALIDATED', 'Rapport Validé'), ('SENT_TO_REQUESTER', 'Transmis Demandeur'), ('COMPLETED', 'Complété'), ('CLOSED', 'Clôturé'), ('REJECTED', 'Rejeté'), ('REQUEST_CREATED', 'Demande Créée'), ('QUOTE_DRAFT', 'Devis En Cours'), ('QUOTE_SENT', 'Devis Envoyé'), ('QUOTE_VALIDATED_BY_CLIENT', 'Devis Accepté'), ('QUOTE_REJECTED_BY_CLIENT', 'Devis Refusé'), ('ORDER_UPLOADED', 'Bon de Commande Uploadé'), ('PAYMENT_PENDING', 'En Attente Paiement'), ('PAYMENT_CONFIRMED', 'Paiement Confirmé'), ('SENT_TO_CLIENT', 'Transmis Client'), ('ARCHIVED', 'Archivé')], default='SUBMITTED', max_length=30),
        ),
    ]
