# Generated by Django 5.1.7 on 2026-03-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_request_order_file_request_order_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='citation_acknowledged',
            field=models.BooleanField(default=False, verbose_name='Citation acknowledgée'),
        ),
    ]
