# Generated by Django 5.1 on 2026-05-22 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_citation_acknowledged"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="service_rating",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("SUBMITTED", "Soumis"),
                    ("VALIDATION_PEDAGOGIQUE", "Validation Pédagogique"),
                    ("VALIDATION_FINANCE", "Validation Finance"),
                    ("PLATFORM_NOTE_GENERATED", "Note Générée"),
                    ("IBTIKAR_SUBMISSION_PENDING", "En attente soumission IBTIKAR"),
                    ("IBTIKAR_CODE_SUBMITTED", "Code IBTIKAR soumis"),
                    ("ASSIGNED", "Assigné"),
                    ("APPOINTMENT_PROPOSED", "RDV Proposé"),
                    ("APPOINTMENT_CONFIRMED", "RDV Confirmé"),
                    ("SAMPLE_RECEIVED", "Échantillon Reçu"),
                    ("ANALYSIS_STARTED", "Analyse Démarrée"),
                    ("ANALYSIS_FINISHED", "Analyse Terminée"),
                    ("REPORT_UPLOADED", "Rapport Uploadé"),
                    ("REPORT_VALIDATED", "Rapport Validé"),
                    ("SENT_TO_REQUESTER", "Transmis Demandeur"),
                    ("COMPLETED", "Complété"),
                    ("CLOSED", "Clôturé"),
                    ("REJECTED", "Rejeté"),
                    ("REQUEST_CREATED", "Demande Créée"),
                    ("QUOTE_DRAFT", "Devis En Cours"),
                    ("QUOTE_SENT", "Devis Envoyé"),
                    ("QUOTE_VALIDATED_BY_CLIENT", "Devis Accepté"),
                    ("QUOTE_REJECTED_BY_CLIENT", "Devis Refusé"),
                    ("ORDER_UPLOADED", "Bon de Commande Uploadé"),
                    ("INVOICE_GENERATED", "Facture Générée"),
                    ("PAYMENT_PENDING", "En Attente Paiement"),
                    ("PAYMENT_CONFIRMED", "Paiement Confirmé"),
                    ("SENT_TO_CLIENT", "Transmis Client"),
                    ("ARCHIVED", "Archivé"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="servicepricing",
            name="unit",
            field=models.CharField(
                blank=True,
                default="forfait",
                max_length=50,
                verbose_name="Unité (ex: par échantillon)",
            ),
        ),
    ]
