# Generated by Django 5.1.7 on 2026-03-31 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_paystat_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_cli_cr_idx',
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='request_chann_idx',
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='request_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='request_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='request_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='request_display_idx',
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='request_arch_idx',
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='request_ch_arch_idx',
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='request_ch_stat_idx',
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='request_stat_cr_idx',
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='request_asgn_stat_idx',
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='request_req_cr_idx',
        ),
        migrations.RemoveIndex(
            model_name='requesthistory',
            name='reqhist_req_cr_idx',
        ),
    ]
