# Generated by Django 5.1 on 2026-05-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_backfill_member_load"),
    ]

    operations = [
        migrations.CreateModel(
            name="SequenceCounter",
            fields=[
                (
                    "scope",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("value", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sequence_counters",
            },
        ),
    ]
