# Generated by Django 5.1.7 on 2026-03-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_invoice_invoice_paystat_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='generated_ibtikar_form',
            field=models.FileField(blank=True, null=True, upload_to='ibtikar_generated/', verbose_name='Generated IBTIKAR Form'),
        ),
    ]
