# Generated by Django 5.1.7 on 2026-04-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_report_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='citation_acknowledged',
        ),
        migrations.AddField(
            model_name='request',
            name='citation_accepted',
            field=models.BooleanField(default=False, verbose_name='Citation accepted'),
        ),
        migrations.AddField(
            model_name='request',
            name='citation_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Citation accepted at'),
        ),
    ]
