# Generated by Django 5.1 on 2026-05-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_seed_sequence_counters"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description_ar",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="description_fr",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_ar",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_fr",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="serviceformfield",
            name="label_ar",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="serviceformfield",
            name="label_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="serviceformfield",
            name="label_fr",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicepricing",
            name="description_ar",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="servicepricing",
            name="description_en",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="servicepricing",
            name="description_fr",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="servicepricing",
            name="name_ar",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Nom du tarif"
            ),
        ),
        migrations.AddField(
            model_name="servicepricing",
            name="name_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Nom du tarif"
            ),
        ),
        migrations.AddField(
            model_name="servicepricing",
            name="name_fr",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Nom du tarif"
            ),
        ),
    ]
