# Generated by Django 5.1.7 on 2026-04-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_citation_accepted_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='generated_platform_note',
            field=models.FileField(blank=True, null=True, upload_to='platform_notes/', verbose_name='Generated Platform Note'),
        ),
        migrations.AddField(
            model_name='request',
            name='generated_reception_form',
            field=models.FileField(blank=True, null=True, upload_to='sample_reception_forms/', verbose_name='Generated Reception Form'),
        ),
    ]
