# Generated by Django 5.1.7 on 2026-04-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_generated_pdfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='hidden_from_archive',
            field=models.BooleanField(default=False, verbose_name='Hidden from archive'),
        ),
    ]
