# Generated by Django 5.1 on 2026-06-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_platformcontent_multilingual"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceformfield",
            name="affects_pricing",
            field=models.BooleanField(
                default=False,
                help_text="Selecting / filling this field changes the price",
            ),
        ),
        migrations.AddField(
            model_name="serviceformfield",
            name="condition_note_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="English notice shown to the user about the extra charge",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="serviceformfield",
            name="condition_note_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="French notice shown to the user about the extra charge",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="serviceformfield",
            name="conditional_logic",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Show/hide & required rules driven by other fields",
            ),
        ),
        migrations.AddField(
            model_name="serviceformfield",
            name="option_pricing",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Per-option pricing map: {"option_value": number}',
            ),
        ),
        migrations.AddField(
            model_name="serviceformfield",
            name="price_modifier_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("add", "Surcharge / Supplément"),
                    ("set", "Forfait / Prix fixe"),
                    ("multiply", "Multiplicateur"),
                ],
                default="",
                help_text="How the field modifies the price (add / set / multiply)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="serviceformfield",
            name="price_modifier_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount, fixed price, or multiplier value",
                max_digits=12,
                null=True,
            ),
        ),
    ]
