# Generated by Django 5.1 on 2026-06-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_serviceformfield_affects_pricing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceformfield",
            name="field_category",
            field=models.CharField(
                choices=[
                    ("parameter", "Question (paramètre du service)"),
                    ("sample_column", "Colonne du tableau d'échantillons"),
                ],
                default="parameter",
                max_length=20,
            ),
        ),
    ]
