# Generated by Django 5.1 on 2026-06-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_serviceformfield_field_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="pricing_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
