# Generated by Django 5.1.7 on 2026-04-01 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_populate_service_form_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['code'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='serviceformfield',
            options={'ordering': ['field_category', 'order', 'sort_order', 'pk'], 'verbose_name': 'Champ de formulaire', 'verbose_name_plural': 'Champs de formulaire'},
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(help_text='Short code (e.g., EGTP-Seq02)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_code',
            field=models.CharField(blank=True, help_text='Official service code (e.g., EGTP-Seq02) — mirrors code field for IBTIKAR forms', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceformfield',
            name='choices_json',
            field=models.JSONField(blank=True, help_text='Options for dropdown/checkbox as JSON list (alternative to options field)', null=True),
        ),
        migrations.AlterField(
            model_name='serviceformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('dropdown', 'Dropdown Select'), ('checkbox', 'Checkbox'), ('textarea', 'Textarea'), ('string', 'Texte'), ('enum', 'Liste'), ('boolean', 'Oui/Non'), ('number', 'Nombre')], default='text', help_text='Widget type for form rendering', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceformfield',
            name='label',
            field=models.CharField(help_text='Display label (bilingual in FR/EN)', max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceformfield',
            name='name',
            field=models.CharField(help_text='Field identifier for data storage', max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceformfield',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='Options for dropdown/checkbox as JSON list'),
        ),
        migrations.AlterField(
            model_name='serviceformfield',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='core.service'),
        ),
        migrations.AlterField(
            model_name='serviceformfield',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
    ]
