# Generated by Django 5.1 on 2026-06-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_ibtikar_balance_declared_at_and_more"),
        ("core", "0019_service_pricing_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="informed_members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Membres ayant un accès en lecture sur cette demande (suivi).",
                related_name="observed_requests",
                to="accounts.memberprofile",
                verbose_name="Membres observateurs",
            ),
        ),
        migrations.AlterField(
            model_name="servicepricing",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("BASE", "Prix de base"),
                    ("PER_SAMPLE", "Par échantillon"),
                    ("PER_PARAMETER", "Par paramètre"),
                    ("URGENCY_SURCHARGE", "Majoration urgence"),
                    ("DISCOUNT", "Remise"),
                    ("OVERRIDE", "Forfait (override total)"),
                ],
                default="BASE",
                max_length=20,
            ),
        ),
    ]
