# Generated by Django 5.1 on 2026-04-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_service_options_alter_serviceformfield_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='pi_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Research Director Email'),
        ),
        migrations.AddField(
            model_name='request',
            name='pi_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Research Director Name'),
        ),
        migrations.AddField(
            model_name='request',
            name='pi_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Research Director Phone'),
        ),
    ]
