# Generated by Django 5.1.7 on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_pi_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceformfield',
            name='help_text_en',
            field=models.CharField(blank=True, help_text='Help text in English', max_length=500),
        ),
        migrations.AddField(
            model_name='serviceformfield',
            name='help_text_fr',
            field=models.CharField(blank=True, help_text='Help text in French', max_length=500),
        ),
        migrations.AlterField(
            model_name='serviceformfield',
            name='field_type',
            field=models.CharField(
                choices=[
                    ('text', 'Text'),
                    ('textarea', 'Textarea'),
                    ('number', 'Number'),
                    ('date', 'Date'),
                    ('select', 'Select'),
                    ('multiselect', 'Multi-select'),
                    ('boolean', 'Yes/No'),
                    ('checkbox', 'Checkbox'),
                    ('string', 'Text (legacy)'),
                    ('enum', 'Enum (legacy)'),
                    ('dropdown', 'Dropdown (legacy)'),
                ],
                default='text',
                help_text='Widget type for form rendering',
                max_length=20,
            ),
        ),
    ]
