# Generated by Django 5.2.15 on 2026-07-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="budget_deducted",
            field=models.BooleanField(
                default=False, verbose_name="Budget IBTIKAR déjà déduit"
            ),
        ),
    ]
