# Generated by Django 5.1 on 2026-04-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_field_channel_to_serviceformfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceformfield',
            name='affects_pricing',
            field=models.BooleanField(default=False, help_text='Whether selecting this option affects the price'),
        ),
        migrations.AddField(
            model_name='serviceformfield',
            name='condition_note_en',
            field=models.CharField(blank=True, default='', help_text='English notice shown to user about additional charges', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceformfield',
            name='condition_note_fr',
            field=models.CharField(blank=True, default='', help_text='French notice shown to user about additional charges', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceformfield',
            name='price_modifier_type',
            field=models.CharField(blank=True, choices=[('add', 'Surcharge / Supplément'), ('set', 'Override / Forfait'), ('multiply', 'Multiplier')], default='', help_text='How this option modifies the price', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceformfield',
            name='price_modifier_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value of the price modifier (amount, new price, or multiplier)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='serviceformfield',
            name='channel',
            field=models.CharField(choices=[('IBTIKAR', 'IBTIKAR'), ('GENOCLAB', 'GENOCLAB'), ('BOTH', 'IBTIKAR & GENOCLAB')], default='BOTH', help_text='Channel availability: IBTIKAR only, GENOCLAB only, or BOTH', max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceformfield',
            name='field_category',
            field=models.CharField(choices=[('parameter', 'Service Parameter'), ('sample_table', 'Sample Table Column'), ('additional_info', 'Additional Info Field')], default='sample_table', help_text='Whether this field is a sample table column or additional info field', max_length=20),
        ),
    ]
