# Generated by Django 5.2.17 on 2026-08-20 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_legacy_payment_verification(apps, schema_editor):
    Request = apps.get_model('core', 'Request')
    for request in Request.objects.filter(
            status='PAYMENT_CONFIRMED', payment_verified_at__isnull=True):
        request.payment_verified_at = request.payment_uploaded_at or request.updated_at
        request.payment_verification_note = (
            'Legacy confirmed payment; verifier identity unavailable before '
            'the separated proof-verification workflow.')
        request.save(update_fields=[
            'payment_verified_at', 'payment_verification_note'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_totp_enabled_user_totp_secret'),
        ('core', '0023_request_budget_deducted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payment_verification_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('VALIDATION_PEDAGOGIQUE', 'Validation Pédagogique'), ('VALIDATION_FINANCE', 'Validation Finance'), ('PLATFORM_NOTE_GENERATED', 'Note Générée'), ('IBTIKAR_SUBMISSION_PENDING', 'En attente soumission IBTIKAR'), ('IBTIKAR_CODE_SUBMITTED', 'Code IBTIKAR soumis'), ('ASSIGNED', 'Assigné'), ('APPOINTMENT_PROPOSED', 'RDV Proposé'), ('APPOINTMENT_CONFIRMED', 'RDV Confirmé'), ('SAMPLE_RECEIVED', 'Échantillon Reçu'), ('ANALYSIS_STARTED', 'Analyse Démarrée'), ('ANALYSIS_FINISHED', 'Analyse Terminée'), ('REPORT_UPLOADED', 'Rapport Uploadé'), ('REPORT_VALIDATED', 'Rapport Validé'), ('SENT_TO_REQUESTER', 'Transmis Demandeur'), ('COMPLETED', 'Complété'), ('CLOSED', 'Clôturé'), ('REJECTED', 'Rejeté'), ('REQUEST_CREATED', 'Demande Créée'), ('QUOTE_DRAFT', 'Devis En Cours'), ('QUOTE_SENT', 'Devis Envoyé'), ('QUOTE_VALIDATED_BY_CLIENT', 'Devis Accepté'), ('QUOTE_REJECTED_BY_CLIENT', 'Devis Refusé'), ('ORDER_UPLOADED', 'Bon de Commande Uploadé'), ('INVOICE_GENERATED', 'Facture Générée'), ('PAYMENT_PENDING', 'En Attente Paiement'), ('PAYMENT_PROOF_UPLOADED', 'Preuve de Paiement Téléversée'), ('PAYMENT_CONFIRMED', 'Paiement Confirmé'), ('SENT_TO_CLIENT', 'Transmis Client'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=30),
        ),
        migrations.RunPython(
            backfill_legacy_payment_verification,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PAYMENT_CONFIRMED'), _negated=True), ('payment_verified_at__isnull', False), _connector='OR'), name='confirmed_payment_has_verification_time'),
        ),
    ]
