# Generated by Django 5.1 on 2026-04-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_pricing_fields_to_serviceformfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='ibtikar_id',
            field=models.CharField(blank=True, default='', help_text='IBTIKAR tracking ID provided by requester (e.g., IDGRSTD00001)', max_length=20, verbose_name='Identifiant IBTIKAR-DGRSDT'),
        ),
        migrations.AddField(
            model_name='request',
            name='tracking_number',
            field=models.CharField(blank=True, default='', help_text='Auto-generated tracking number for GENOCLAB (GCL-YYYY-XXXXX)', max_length=20, verbose_name='Numéro de suivi'),
        ),
        migrations.AddField(
            model_name='service',
            name='citation_clause_en',
            field=models.TextField(blank=True, default='', help_text='Mandatory citation text for IBTIKAR requests (English)', verbose_name='Citation clause (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='citation_clause_fr',
            field=models.TextField(blank=True, default='', help_text='Texte de citation obligatoire pour les demandes IBTIKAR (Français)', verbose_name='Clause de citation (FR)'),
        ),
        migrations.AddField(
            model_name='service',
            name='turnaround_genoclab',
            field=models.IntegerField(default=7, help_text='Turnaround time in business days for GENOCLAB channel', verbose_name='Délai GENOCLAB (jours)'),
        ),
        migrations.AddField(
            model_name='service',
            name='turnaround_ibtikar',
            field=models.IntegerField(default=7, help_text='Turnaround time in business days for IBTIKAR channel', verbose_name='Délai IBTIKAR (jours)'),
        ),
        migrations.AddField(
            model_name='service',
            name='turnaround_unit',
            field=models.CharField(choices=[('business_days', 'Jours ouvrables / Business days'), ('calendar_days', 'Jours calendaires / Calendar days'), ('weeks', 'Semaines / Weeks')], default='business_days', max_length=20, verbose_name='Unité de délai'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('VALIDATION_PEDAGOGIQUE', 'Validation Pédagogique'), ('VALIDATION_FINANCE', 'Validation Finance'), ('PLATFORM_NOTE_GENERATED', 'Note Générée'), ('IBTIKAR_SUBMISSION_PENDING', 'En attente soumission IBTIKAR'), ('IBTIKAR_CODE_SUBMITTED', 'Code IBTIKAR soumis'), ('ASSIGNED', 'Assigné'), ('PENDING_ACCEPTANCE', 'En Attente Acceptation'), ('APPOINTMENT_PROPOSED', 'RDV Proposé'), ('APPOINTMENT_RESCHEDULING_REQUESTED', 'Reprogrammation Demandée'), ('APPOINTMENT_CONFIRMED', 'RDV Confirmé'), ('SAMPLE_RECEIVED', 'Échantillon Reçu'), ('ANALYSIS_STARTED', 'Analyse Démarrée'), ('ANALYSIS_FINISHED', 'Analyse Terminée'), ('REPORT_UPLOADED', 'Rapport Uploadé'), ('ADMIN_REVIEW', 'Révision Admin'), ('REPORT_VALIDATED', 'Rapport Validé'), ('SENT_TO_REQUESTER', 'Transmis Demandeur'), ('COMPLETED', 'Complété'), ('CLOSED', 'Clôturé'), ('REJECTED', 'Rejeté'), ('REQUEST_CREATED', 'Demande Créée'), ('QUOTE_DRAFT', 'Devis En Cours'), ('QUOTE_SENT', 'Devis Envoyé'), ('QUOTE_VALIDATED_BY_CLIENT', 'Devis Accepté'), ('QUOTE_REJECTED_BY_CLIENT', 'Devis Refusé'), ('ORDER_UPLOADED', 'Bon de Commande Uploadé'), ('PAYMENT_PENDING', 'En Attente Paiement'), ('PAYMENT_UPLOADED', 'Reçu de Paiement Uploadé'), ('PAYMENT_CONFIRMED', 'Paiement Confirmé'), ('INVOICE_GENERATED', 'Facture Générée'), ('SENT_TO_CLIENT', 'Transmis Client'), ('ARCHIVED', 'Archivé')], default='SUBMITTED', max_length=40),
        ),
        migrations.AlterField(
            model_name='service',
            name='turnaround_days',
            field=models.IntegerField(default=7, help_text='Deprecated: use turnaround_ibtikar and turnaround_genoclab'),
        ),
    ]
