# Generated by Django 5.1 on 2026-04-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_accepted_declined_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceformfield',
            name='conditional_logic',
            field=models.JSONField(blank=True, default=list, help_text='Conditional rules: [{"trigger_field": "field_name", "trigger_value": "value", "actions": ["show", "make_required"]}]'),
        ),
    ]
