# Generated by Django 5.2.17 on 2026-09-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_shared_rate_limit_bucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_estimates', models.BooleanField(default=False, verbose_name='Afficher les estimations financières au client')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Validité de publication des estimations')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='request',
            name='billing_channel',
            field=models.CharField(choices=[('GENOCLAB', 'GenoClab'), ('OHB', 'OHB — Opérations Hors Budget')], default='GENOCLAB', max_length=10),
        ),
        migrations.AddField(
            model_name='request',
            name='quote_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='quote_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicepricing',
            name='channel',
            field=models.CharField(choices=[('IBTIKAR', 'IBTIKAR'), ('GENOCLAB', 'GENOCLAB'), ('OHB', 'OHB'), ('BOTH', 'Tous les canaux')], default='BOTH', max_length=10),
        ),
    ]
