# Generated by Django 5.2.17 on 2026-09-06 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_financial_release_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_channel',
            field=models.CharField(choices=[('GENOCLAB', 'GenoClab'), ('OHB', 'OHB — Opérations Hors Budget')], default='GENOCLAB', max_length=10),
        ),
        migrations.AddField(
            model_name='request',
            name='billing_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='billing_assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='billing_channel',
            field=models.CharField(choices=[('GENOCLAB', 'GenoClab'), ('OHB', 'OHB — Opérations Hors Budget')], default='GENOCLAB', max_length=10),
        ),
    ]
