# Generated by Django 5.1 on 2026-04-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_serviceformfield_conditional_logic'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceformfield',
            name='option_pricing',
            field=models.JSONField(blank=True, default=dict, help_text='Per-option pricing: {"option_value": 500, "other_option": 1000} - for multi-select fields'),
        ),
    ]
