# Generated by Django 5.2.17 on 2026-09-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_internal_ohb_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payment_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_order_file',
            field=models.FileField(blank=True, null=True, upload_to='payment_orders/'),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_order_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_order_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
