# Generated by Django 5.1 on 2026-04-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_serviceformfield_option_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completion_points_awarded',
            field=models.BooleanField(default=False, verbose_name='Completion points awarded'),
        ),
    ]
