# Generated by Django 5.2.17 on 2026-09-06 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_payment_order_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('billing_channel', 'OHB'), _negated=True), models.Q(('vat_rate', 0), ('vat_amount', 0)), _connector='OR'), name='ohb_invoice_without_vat'),
        ),
        migrations.AddConstraint(
            model_name='servicepricing',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='service_pricing_dates_ordered'),
        ),
    ]
