# Generated by Django 5.1 on 2026-04-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_request_deleted_at_request_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceformfield',
            name='max_selections',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of selections allowed for multi-select fields (security constraint)', null=True),
        ),
    ]
