# Generated by Django 5.2.17 on 2026-09-06 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_financial_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsettings',
            name='invoice_payment_days',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(3650)], verbose_name='Délai de paiement en jours'),
        ),
        migrations.AddField(
            model_name='financialsettings',
            name='invoice_payment_method',
            field=models.CharField(default='Virement bancaire', max_length=150, verbose_name='Mode de paiement des factures'),
        ),
    ]
