# Generated by Django 5.2.17 on 2026-09-06 23:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_invoice_payment_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.19'), max_digits=5),
        ),
    ]
