# Generated by Django 5.1 on 2026-04-04 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_performance_indexes'),
        ('core', '0032_service_field_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reschedule_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times appointment has been rescheduled', verbose_name='Reschedule Count'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('VALIDATION_PEDAGOGIQUE', 'Validation Pédagogique'), ('VALIDATION_FINANCE', 'Validation Finance'), ('PLATFORM_NOTE_GENERATED', 'Note Générée'), ('IBTIKAR_SUBMISSION_PENDING', 'En attente soumission IBTIKAR'), ('IBTIKAR_CODE_SUBMITTED', 'Code IBTIKAR soumis'), ('ASSIGNED', 'Assigné'), ('PENDING_ACCEPTANCE', 'En Attente Acceptation'), ('ACCEPTED', 'Accepté'), ('DECLINED', 'Refusé'), ('APPOINTMENT_PROPOSED', 'RDV Proposé'), ('APPOINTMENT_RESCHEDULING_REQUESTED', 'Reprogrammation Demandée'), ('APPOINTMENT_CONFIRMED', 'RDV Confirmé'), ('SAMPLE_RECEIVED', 'Échantillon Reçu'), ('ANALYSIS_STARTED', 'Analyse Démarrée'), ('ANALYSIS_FINISHED', 'Analyse Terminée'), ('REPORT_UPLOADED', 'Rapport Uploadé'), ('REPORT_VALIDATED', 'Rapport Validé'), ('SENT_TO_REQUESTER', 'Transmis Demandeur'), ('COMPLETED', 'Complété'), ('CLOSED', 'Clôturé'), ('REJECTED', 'Rejeté'), ('REQUEST_CREATED', 'Demande Créée'), ('QUOTE_DRAFT', 'Devis En Cours'), ('QUOTE_SENT', 'Devis Envoyé'), ('QUOTE_VALIDATED_BY_CLIENT', 'Devis Accepté'), ('QUOTE_REJECTED_BY_CLIENT', 'Devis Refusé'), ('ORDER_UPLOADED', 'Bon de Commande Uploadé'), ('PAYMENT_PENDING', 'En Attente Paiement'), ('PAYMENT_UPLOADED', 'Reçu de Paiement Uploadé'), ('PAYMENT_CONFIRMED', 'Paiement Confirmé'), ('INVOICE_GENERATED', 'Facture Générée'), ('INVOICE_SENT', 'Facture Transmise'), ('SENT_TO_CLIENT', 'Transmis Client'), ('ARCHIVED', 'Archivé')], default='SUBMITTED', max_length=40),
        ),
        migrations.AlterField(
            model_name='servicefieldtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['channel', 'status', 'updated_at'], name='requests_channel_f26cad_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['requester', 'status'], name='requests_request_0b77d5_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['assigned_to', 'status', 'updated_at'], name='requests_assigne_83c0ad_idx'),
        ),
    ]
