# Generated by Django 5.1 on 2026-04-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepricing',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Prix en DZD. Les modifications s'appliquent aux nouvelles demandes uniquement. Les demandes en cours conservent leur prix validé.", max_digits=12, verbose_name='Montant (DZD)'),
        ),
    ]
