# Generated by Django 5.1 on 2026-04-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_declared_balance_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='declared_balance_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Declared balance timestamp'),
        ),
    ]
