# Generated by Django 5.1 on 2026-04-05 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_declared_balance_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenoclabSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='GENOCLAB', max_length=200, verbose_name='Nom de la société')),
                ('company_subtitle', models.CharField(default="Plateforme d'Analyses Génomiques", max_length=200, verbose_name='Sous-titre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='genoclab/logo/', verbose_name='Logo GENOCLAB')),
                ('address_line1', models.CharField(blank=True, default='', max_length=200, verbose_name='Adresse ligne 1')),
                ('address_line2', models.CharField(blank=True, default='', max_length=200, verbose_name='Adresse ligne 2')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, default='', verbose_name='Site web')),
                ('bank_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nom de la banque')),
                ('account_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Numéro de compte')),
                ('rib', models.CharField(blank=True, default='', max_length=50, verbose_name='RIB')),
                ('swift_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Code SWIFT')),
                ('rc_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Numéro RC')),
                ('nif', models.CharField(blank=True, default='', max_length=50, verbose_name='NIF')),
                ('ai', models.CharField(blank=True, default='', max_length=50, verbose_name='AI')),
                ('quote_validity_days', models.IntegerField(default=30, verbose_name='Validité du devis (jours)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='Taux de TVA (%)')),
                ('quote_footer_text', models.TextField(blank=True, default='Ce devis est établi sous réserve de disponibilité. Les conditions de paiement sont mentionnées ci-dessus.', verbose_name='Texte de pied de page du devis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genoclab_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètres GENOCLAB',
                'verbose_name_plural': 'Paramètres GENOCLAB',
                'db_table': 'genoclab_settings',
            },
        ),
    ]
