# Generated by Django 5.1 on 2026-04-05 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_genoclab_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('items', models.JSONField(default=list, verbose_name='Lignes du devis')),
                ('subtotal_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('admin_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('report_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_before_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remise')),
                ('discount_reason', models.TextField(blank=True, default='', verbose_name='Raison de la remise')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('terms', models.TextField(blank=True, default='', verbose_name='Conditions')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('rejected', 'Refusé'), ('expired', 'Expiré')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('is_current', models.BooleanField(default=True, verbose_name='Version actuelle')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_created', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.request')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'db_table': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
