# Generated by Django 5.1 on 2026-04-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_quote_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceformfield',
            name='price_modifier_scope',
            field=models.CharField(blank=True, choices=[('per_sample', 'Per Sample / Par échantillon'), ('total', 'Total / Montant total')], default='total', help_text='Apply modifier per sample (added before count/multiplier) or to final total', max_length=20),
        ),
    ]
