# Generated by Django 5.2.17 on 2026-09-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_arabic_footer_platform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='appointment_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='request',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
