# Generated by Django 5.1 on 2026-04-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_performance_indexes'),
        ('core', '0038_add_price_modifier_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='informed_members',
            field=models.ManyToManyField(blank=True, help_text='Members informed about this request (read-only access)', related_name='observed_requests', to='accounts.memberprofile'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('VALIDATION_PEDAGOGIQUE', 'Validation Pédagogique'), ('VALIDATION_FINANCE', 'Validation Finance'), ('PLATFORM_NOTE_GENERATED', 'Note Générée'), ('IBTIKAR_SUBMISSION_PENDING', 'En attente soumission IBTIKAR'), ('IBTIKAR_CODE_SUBMITTED', 'Code IBTIKAR soumis'), ('ASSIGNED', 'Assigné'), ('PENDING_ACCEPTANCE', 'En Attente Acceptation'), ('ACCEPTED', 'Accepté'), ('DECLINED', 'Refusé'), ('APPOINTMENT_PROPOSED', 'RDV Proposé'), ('APPOINTMENT_RESCHEDULING_REQUESTED', 'Reprogrammation Demandée'), ('APPOINTMENT_CONFIRMED', 'RDV Confirmé'), ('SAMPLE_RECEIVED', 'Échantillon Reçu'), ('ANALYSIS_STARTED', 'Analyse Démarrée'), ('ANALYSIS_FINISHED', 'Analyse Terminée'), ('REPORT_UPLOADED', 'Rapport Uploadé'), ('REPORT_VALIDATED', 'Rapport Validé'), ('SENT_TO_REQUESTER', 'Transmis Demandeur'), ('COMPLETED', 'Complété'), ('CLOSED', 'Clôturé'), ('REJECTED', 'Rejeté'), ('ADMINISTRATIVELY_CLOSED', 'Fermé Administrativement'), ('REQUEST_CREATED', 'Demande Créée'), ('QUOTE_DRAFT', 'Devis En Cours'), ('QUOTE_SENT', 'Devis Envoyé'), ('QUOTE_VALIDATED_BY_CLIENT', 'Devis Accepté'), ('QUOTE_REJECTED_BY_CLIENT', 'Devis Refusé'), ('ORDER_UPLOADED', 'Bon de Commande Uploadé'), ('PAYMENT_PENDING', 'En Attente Paiement'), ('PAYMENT_UPLOADED', 'Reçu de Paiement Uploadé'), ('PAYMENT_CONFIRMED', 'Paiement Confirmé'), ('INVOICE_GENERATED', 'Facture Générée'), ('INVOICE_SENT', 'Facture Transmise'), ('SENT_TO_CLIENT', 'Transmis Client'), ('ARCHIVED', 'Archivé')], default='SUBMITTED', max_length=40),
        ),
    ]
