# Generated by Django 5.1 on 2026-04-10 13:20

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_request_informed_members_alter_request_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Homepage', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Homepage',
                'verbose_name_plural': 'Homepages',
                'db_table': 'homepage',
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('partners', 'Partners'), ('services', 'Services'), ('stats', 'Stats'), ('about', 'About'), ('contact', 'Contact'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.homepage_section_image_upload_to)),
                ('link_url', models.URLField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.homepage')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_section_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'homepage_sections',
                'ordering': ['position', 'pk'],
                'unique_together': {('homepage', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='HomepageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('card', 'Card'), ('logo', 'Logo'), ('button', 'Button/CTA'), ('text', 'Text'), ('image', 'Image'), ('stat', 'Stat')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField(blank=True, default='')),
                ('link_url', models.URLField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.homepage_block_image_upload_to)),
                ('image_alt', models.CharField(blank=True, default='', max_length=255)),
                ('cta_style', models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('ghost', 'Ghost')], default='primary', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_block_updates', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.homepagesection')),
            ],
            options={
                'db_table': 'homepage_blocks',
                'ordering': ['position', 'pk'],
            },
        ),
    ]
