# Generated by Django 5.2.17 on 2026-09-18 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_arabic_plagenor_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IbtikarSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.JSONField(default=dict)),
                ('schema_hash', models.CharField(max_length=64)),
                ('applicant', models.JSONField(default=dict)),
                ('parameters', models.JSONField(default=dict)),
                ('samples', models.JSONField(default=list)),
                ('staff', models.JSONField(default=dict)),
                ('estimate', models.JSONField(default=dict)),
                ('legacy_data', models.JSONField(blank=True, default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ibtikar_form', to='core.request')),
            ],
        ),
        migrations.CreateModel(
            name='IbtikarRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.ibtikarsubmission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('submission', 'revision'), name='ibtikar_revision_unique')],
            },
        ),
        migrations.CreateModel(
            name='IbtikarAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='ibtikar_attachments/%Y/%m/')),
                ('sha256', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.ibtikarsubmission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('submission', 'field_name'), name='ibtikar_active_attachment_unique')],
            },
        ),
    ]
