# Generated by Django 5.1 on 2026-04-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_pdfformfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepricing',
            name='pricing_type',
            field=models.CharField(choices=[('BASE', 'Prix de base'), ('PER_SAMPLE', 'Par échantillon'), ('PER_PARAMETER', 'Par paramètre'), ('URGENCY_SURCHARGE', 'Majoration urgence'), ('DISCOUNT', 'Remise'), ('OVERRIDE', 'Forfait (override total)')], default='BASE', max_length=20),
        ),
    ]
