# Generated by Django 5.2.17 on 2026-09-21 00:00

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9._-]{0,31}$')], verbose_name='Code interne')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation française')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Désignation anglaise')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Désignation arabe')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('can_store', models.BooleanField(default=False, verbose_name='Stockage autorisé')),
                ('cold_storage', models.BooleanField(default=False, verbose_name='Stockage réfrigéré')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreeLock',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9._-]{0,31}$')], verbose_name='Code interne')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation française')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Désignation anglaise')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Désignation arabe')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='erp.category', verbose_name='Catégorie parente')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9._-]{0,31}$')], verbose_name='Code interne')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation française')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Désignation anglaise')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Désignation arabe')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('temperature_target', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Température cible (°C)')),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Température minimale (°C)')),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Température maximale (°C)')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité (positions)')),
                ('grid_rows', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Lignes de la boîte')),
                ('grid_columns', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Colonnes de la boîte')),
                ('notes', models.TextField(blank=True, verbose_name='Consignes et observations')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='erp.location', verbose_name='Emplacement parent')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.locationtype', verbose_name='Type d’emplacement')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9._-]{0,31}$')], verbose_name='Code interne')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation française')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Désignation anglaise')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Désignation arabe')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_supplier', models.BooleanField(default=True, verbose_name='Fournisseur')),
                ('is_manufacturer', models.BooleanField(default=False, verbose_name='Fabricant')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse électronique')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Téléphone')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('is_supplier', True), ('is_manufacturer', True), _connector='OR'), name='erp_party_has_role')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9._-]{0,31}$')], verbose_name='Code interne')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation française')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Désignation anglaise')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Désignation arabe')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('manufacturer_reference', models.CharField(blank=True, max_length=120, verbose_name='Référence fabricant')),
                ('catalog_reference', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Référence catalogue')),
                ('cas', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Numéro CAS')),
                ('concentration', models.CharField(blank=True, max_length=120, verbose_name='Concentration')),
                ('grade', models.CharField(blank=True, max_length=120, verbose_name='Grade / pureté')),
                ('format', models.CharField(blank=True, max_length=120, verbose_name='Format')),
                ('packaging', models.CharField(blank=True, max_length=255, verbose_name='Conditionnement décrit')),
                ('criticality', models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Haute'), ('MEDIUM', 'Moyenne'), ('LOW', 'Faible')], default='MEDIUM', max_length=10, verbose_name='Criticité')),
                ('minimum_stock', models.DecimalField(decimal_places=6, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock minimal')),
                ('safety_stock', models.DecimalField(decimal_places=6, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock de sécurité')),
                ('reorder_point', models.DecimalField(decimal_places=6, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seuil de réapprovisionnement')),
                ('target_stock', models.DecimalField(decimal_places=6, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock cible')),
                ('order_multiple', models.DecimalField(decimal_places=6, default=1, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Multiple de commande')),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Délai fournisseur (jours)')),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée de conservation (jours)')),
                ('after_open_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stabilité après ouverture (jours)')),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Température minimale (°C)')),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Température maximale (°C)')),
                ('light_sensitive', models.BooleanField(blank=True, null=True, verbose_name='Sensible à la lumière')),
                ('specifications', models.TextField(blank=True, verbose_name='Spécifications techniques')),
                ('storage_instructions', models.TextField(blank=True, verbose_name='Consignes de conservation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.category', verbose_name='Catégorie')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufactured_articles', to='erp.party', verbose_name='Fabricant')),
                ('preferred_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_articles', to='erp.party', verbose_name='Fournisseur préféré')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9._-]{0,31}$')], verbose_name='Code interne')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation française')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Désignation anglaise')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Désignation arabe')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('dimension', models.CharField(choices=[('COUNT', 'Pièces'), ('VOLUME', 'Volume'), ('MASS', 'Masse'), ('TEST', 'Tests'), ('REACTION', 'Réactions'), ('PACKAGE', 'Conditionnement'), ('OTHER', 'Autre dimension')], max_length=16, verbose_name='Dimension')),
                ('factor', models.DecimalField(decimal_places=9, default=1, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('1E-9'))], verbose_name='Facteur vers l’unité de référence')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('factor__gt', 0)), name='erp_unit_factor_positive')],
            },
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire')),
                ('currency', models.CharField(default='DZD', max_length=3, verbose_name='Devise')),
                ('observed_on', models.DateField(verbose_name='Date de référence')),
                ('source', models.CharField(max_length=500, verbose_name='Source du prix')),
                ('snapshot', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='erp.article')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.party', verbose_name='Fournisseur')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.unit', verbose_name='Unité du prix')),
            ],
            options={
                'ordering': ['-observed_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factor', models.DecimalField(decimal_places=9, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('1E-9'))], verbose_name='Quantité dans l’unité de gestion')),
                ('justification', models.CharField(max_length=500, verbose_name='Justification de la conversion')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='erp.article')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.unit', verbose_name='Unité alternative')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='base_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.unit', verbose_name='Unité de gestion'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(max_length=32)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='erp_auditev_entity__4546f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(choices=[('view_catalog', 'Consulter le catalogue'), ('edit_catalog', 'Gérer le catalogue'), ('view_storage', 'Consulter les emplacements'), ('edit_storage', 'Gérer les emplacements'), ('view_cost', 'Consulter les coûts'), ('edit_cost', 'Enregistrer les prix')], max_length=32, verbose_name='Permission')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_grants', to=settings.AUTH_USER_MODEL, verbose_name='Membre de l’équipe')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.category', verbose_name='Catégorie autorisée')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.location', verbose_name='Périmètre de stockage')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'capability', 'active'], name='erp_accessg_user_id_32301d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.PositiveIntegerField()),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant_links', to='erp.location')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestor_links', to='erp.location')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ancestor', 'descendant'), name='erp_location_closure_unique'), models.CheckConstraint(condition=models.Q(models.Q(('ancestor', models.F('descendant')), ('depth', 0)), models.Q(('depth__gt', 0), models.Q(('ancestor', models.F('descendant')), _negated=True)), _connector='OR'), name='erp_closure_depth_matches')],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['parent', 'active'], name='erp_locatio_parent__c5dbd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('pk')), _negated=True), name='erp_location_not_own_parent'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('temperature_min__isnull', True), ('temperature_max__isnull', True), ('temperature_min__lte', models.F('temperature_max')), _connector='OR'), name='erp_location_temperature_order'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__isnull', True), ('capacity__gt', 0), _connector='OR'), name='erp_location_positive_capacity'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grid_columns__isnull', True), ('grid_rows__isnull', True)), models.Q(('grid_columns__gt', 0), ('grid_columns__isnull', False), ('grid_rows__gt', 0), ('grid_rows__isnull', False)), _connector='OR'), name='erp_location_grid_complete'),
        ),
        migrations.AddConstraint(
            model_name='priceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='erp_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='articleconversion',
            constraint=models.UniqueConstraint(fields=('article', 'unit'), name='erp_article_unit_unique'),
        ),
        migrations.AddConstraint(
            model_name='articleconversion',
            constraint=models.CheckConstraint(condition=models.Q(('factor__gt', 0)), name='erp_conversion_positive'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'active'], name='erp_article_categor_ec6cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['criticality', 'active'], name='erp_article_critica_5e4416_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(models.F('manufacturer'), django.db.models.functions.text.Lower('manufacturer_reference'), condition=models.Q(('manufacturer_reference', ''), _negated=True), name='erp_article_manufacturer_ref'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_stock__gte', 0), ('order_multiple__gt', 0), ('reorder_point__gte', 0), ('safety_stock__gte', 0), ('target_stock__gte', 0)), name='erp_article_thresholds_positive'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('temperature_min__isnull', True), ('temperature_max__isnull', True), ('temperature_min__lte', models.F('temperature_max')), _connector='OR'), name='erp_article_temperature_order'),
        ),
    ]
