# Generated by Django 5.2.17 on 2026-09-21 00:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_immutable_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='articleconversion',
            name='erp_conversion_positive',
        ),
        migrations.RemoveConstraint(
            model_name='priceobservation',
            name='erp_price_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='unit',
            name='erp_unit_factor_positive',
        ),
        migrations.RemoveField(
            model_name='article',
            name='concentration',
        ),
        migrations.AddField(
            model_name='article',
            name='concentration_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.unit', verbose_name='Unité de concentration'),
        ),
        migrations.AddField(
            model_name='article',
            name='concentration_value',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Concentration'),
        ),
        migrations.AddField(
            model_name='article',
            name='consumption_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.unit', verbose_name='Unité de consommation'),
        ),
        migrations.AddField(
            model_name='article',
            name='purchase_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.unit', verbose_name='Unité d’achat'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('concentration_unit__isnull', True), ('concentration_value__isnull', True)), models.Q(('concentration_unit__isnull', False), ('concentration_value__gte', 0), ('concentration_value__isnull', False), ('concentration_value__lte', Decimal('999999999999999.999999999'))), _connector='OR'), name='erp_concentration_complete', violation_error_message='Renseignez ensemble la concentration et son unité.'),
        ),
        migrations.AddConstraint(
            model_name='articleconversion',
            constraint=models.CheckConstraint(condition=models.Q(('factor__gt', 0), ('factor__lte', Decimal('999999999999999.999999999'))), name='erp_conversion_positive'),
        ),
        migrations.AddConstraint(
            model_name='priceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('amount__lte', Decimal('9999999999999999.99'))), name='erp_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(('factor__gt', 0), ('factor__lte', Decimal('999999999999999.999999999'))), name='erp_unit_factor_positive'),
        ),
    ]
