# Generated by Django 5.2.17 on 2026-09-21 13:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_commercial_document_defaults'),
        ('erp', '0003_structured_units_and_finite_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CdcDossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.CharField(choices=[('reagents', 'Réactifs et consommables'), ('equipment', 'Équipements scientifiques'), ('works', 'Aménagement et travaux')], max_length=12, verbose_name='Famille documentaire')),
                ('reference', models.CharField(max_length=90, unique=True, verbose_name='Référence du dossier')),
                ('data', models.JSONField(default=dict, editable=False)),
                ('revision_number', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blind', models.BooleanField(default=True, verbose_name='Masquer le stock théorique pendant le comptage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='capability',
            field=models.CharField(choices=[('view_catalog', 'Consulter le catalogue'), ('edit_catalog', 'Gérer le catalogue'), ('view_storage', 'Consulter les emplacements'), ('edit_storage', 'Gérer les emplacements'), ('view_cost', 'Consulter les coûts'), ('edit_cost', 'Enregistrer les prix'), ('view_stock', 'Consulter le stock'), ('receive_stock', 'Réceptionner le stock'), ('consume_stock', 'Enregistrer les consommations'), ('transfer_stock', 'Transférer le stock'), ('reserve_stock', 'Réserver le stock'), ('control_stock', 'Contrôler les lots et les sorties'), ('inventory', 'Réaliser un inventaire'), ('view_biobank', 'Consulter l’échantillothèque'), ('manage_biobank', 'Gérer l’échantillothèque'), ('view_planning', 'Consulter les besoins prévisionnels'), ('edit_planning', 'Préparer les besoins prévisionnels')], max_length=32, verbose_name='Permission'),
        ),
        migrations.CreateModel(
            name='CdcGeneration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('docx', models.BinaryField()),
                ('pdf', models.BinaryField()),
                ('docx_sha256', models.CharField(max_length=64)),
                ('pdf_sha256', models.CharField(max_length=64)),
                ('pages', models.PositiveIntegerField()),
                ('checks', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CdcApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement', models.CharField(max_length=500, verbose_name='Justification de validation')),
                ('reviewed_pages', models.PositiveIntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval', to='erp.cdcdossier')),
                ('generation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval', to='erp.cdcgeneration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CdcLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=180, verbose_name='Intitulé du lot en français')),
                ('name_ar', models.CharField(blank=True, max_length=240, verbose_name='Intitulé du lot en arabe')),
                ('source_slot', models.PositiveSmallIntegerField(editable=False)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='erp.cdcdossier')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CdcItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_key', models.CharField(editable=False, max_length=48)),
                ('position', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=True, verbose_name='Retenir cet article')),
                ('article_snapshot', models.JSONField(default=dict, editable=False)),
                ('designation', models.TextField(verbose_name='Désignation')),
                ('specifications', models.TextField(blank=True, verbose_name='Spécifications techniques')),
                ('unit_label', models.CharField(max_length=100, verbose_name='Unité documentaire')),
                ('base_factor', models.DecimalField(blank=True, decimal_places=9, editable=False, max_digits=24, null=True)),
                ('packaging', models.TextField(blank=True, verbose_name='Conditionnement')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Quantité prévue')),
                ('details', models.TextField(blank=True, verbose_name='Précisions complémentaires')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire estimé hors taxes')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de taxe (%)')),
                ('price_source', models.CharField(blank=True, max_length=500, verbose_name='Source de l’estimation')),
                ('currency', models.CharField(default='DZD', max_length=3, verbose_name='Devise')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cdc_items', to='erp.article', verbose_name='Article du référentiel commun')),
                ('purchase_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.unit', verbose_name='Unité d’achat structurée')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='erp.cdclot')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CdcRevision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('estimates', models.JSONField(default=list)),
                ('sha256', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='erp.cdcdossier')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='cdcgeneration',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='erp.cdcrevision'),
        ),
        migrations.CreateModel(
            name='StockContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9._-]{0,31}$')], verbose_name='Code interne')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation française')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Désignation anglaise')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Désignation arabe')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de contrôle'), ('QUARANTINE', 'Quarantaine'), ('AVAILABLE', 'Accepté / disponible'), ('REJECTED', 'Rejeté'), ('RECALLED', 'Rappelé'), ('DESTROYED', 'Détruit')], default='PENDING', max_length=12, verbose_name='Contrôle du contenant')),
                ('stability_days', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=18, verbose_name='Stock physique')),
                ('reserved', models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=18, verbose_name='Stock réservé')),
                ('opened_on', models.DateField(blank=True, null=True, verbose_name='Date d’ouverture')),
                ('use_by', models.DateField(blank=True, db_index=True, editable=False, null=True, verbose_name='Date limite d’utilisation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_containers', to='erp.location')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theoretical_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Quantité physique comptée')),
                ('container_version', models.PositiveIntegerField()),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('needs_recount', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Observation de comptage')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='erp.inventorycampaign')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.location')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.stockcontainer')),
            ],
            options={
                'ordering': ['container__code'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9._-]{0,31}$')], verbose_name='Code interne')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation française')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Désignation anglaise')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Désignation arabe')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('manufacturer_lot', models.CharField(db_index=True, max_length=120, verbose_name='Lot fabricant')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='Numéro de série')),
                ('manufactured_on', models.DateField(blank=True, null=True, verbose_name='Date de fabrication')),
                ('expires_on', models.DateField(blank=True, db_index=True, null=True, verbose_name='Péremption fabricant')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de contrôle'), ('QUARANTINE', 'Quarantaine'), ('AVAILABLE', 'Accepté / disponible'), ('REJECTED', 'Rejeté'), ('RECALLED', 'Rappelé'), ('DESTROYED', 'Détruit')], default='PENDING', max_length=12, verbose_name='État du lot')),
                ('origin', models.CharField(choices=[('PURCHASE', 'Achat'), ('PREPARATION', 'Préparation interne')], default='PURCHASE', max_length=16, verbose_name='Origine')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Code fabricant / GS1')),
                ('specifications_snapshot', models.JSONField(default=dict, editable=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='erp.article')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockcontainer',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='erp.stocklot'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('INITIAL', 'Stock initial'), ('RECEIPT', 'Réception'), ('CONSUMPTION', 'Consommation'), ('TRANSFER', 'Transfert'), ('RESERVATION', 'Réservation'), ('RELEASE', 'Libération'), ('RETURN', 'Retour'), ('CORRECTION', 'Contre-passation'), ('INVENTORY', 'Ajustement d’inventaire'), ('LOSS', 'Perte'), ('BREAKAGE', 'Casse'), ('CONTAMINATION', 'Contamination'), ('EXPIRY', 'Péremption'), ('DESTRUCTION', 'Destruction'), ('EXIT', 'Sortie définitive'), ('PREPARATION', 'Préparation interne')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='Motif')),
                ('snapshot', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_stock_movements', to='core.request')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='erp.stockmovement')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity_delta', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('reserved_delta', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('snapshot', models.JSONField(default=dict)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='erp.stockcontainer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.location')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='erp.stockmovement')),
            ],
        ),
        migrations.AddField(
            model_name='inventorycampaign',
            name='adjustment',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_campaign', to='erp.stockmovement'),
        ),
        migrations.CreateModel(
            name='InternalPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protocol_reference', models.CharField(max_length=255, verbose_name='Protocole / SOP')),
                ('prepared_on', models.DateField(verbose_name='Date de préparation')),
                ('concentration', models.CharField(blank=True, max_length=120, verbose_name='Concentration documentée')),
                ('sources', models.JSONField(default=list)),
                ('output_lot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='preparation', to='erp.stocklot')),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='erp.stockmovement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_reference', models.CharField(blank=True, max_length=120, verbose_name='Commande / marché')),
                ('ordered_on', models.DateField(blank=True, null=True, verbose_name='Date de commande')),
                ('received_on', models.DateField(verbose_name='Date de réception')),
                ('ordered_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Quantité commandée (unité de gestion)')),
                ('received_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('condition', models.CharField(max_length=255, verbose_name='État à la réception')),
                ('cold_chain_ok', models.BooleanField(blank=True, null=True, verbose_name='Chaîne du froid respectée')),
                ('control_notes', models.TextField(blank=True, verbose_name='Contrôle de réception')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Prix unitaire (unité de gestion)')),
                ('currency', models.CharField(default='DZD', max_length=3, verbose_name='Devise')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.stockcontainer')),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='erp.stockmovement')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.party')),
            ],
            options={
                'ordering': ['-received_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=255, verbose_name='Run / projet / justification')),
                ('remaining', models.DecimalField(decimal_places=6, max_digits=18)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='erp.stockcontainer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='erp.stockmovement')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_reservations', to='core.request')),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('INVENTORY', 'Inventaire physique'), ('CDC', 'Cahier des charges'), ('RECEIPT', 'Contrôle de réception'), ('TEMPERATURE', 'Relevé de température'), ('PLAN', 'Plan d’approvisionnement'), ('CONTROL', 'Contrôle opérationnel')], max_length=16, verbose_name='Type de tâche')),
                ('title', models.CharField(max_length=255, verbose_name='Intitulé')),
                ('instructions', models.TextField(blank=True, verbose_name='Consignes')),
                ('due_on', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('NORMAL', 'Normale'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='NORMAL', max_length=8, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ASSIGNED', 'Affecté'), ('IN_PROGRESS', 'En cours'), ('SUBMITTED', 'Soumis à validation'), ('CHANGES_REQUESTED', 'Corrections demandées'), ('APPROVED', 'Validé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('allow_costs', models.BooleanField(default=False, verbose_name='Autoriser les estimations de ce dossier')),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_work_items', to=settings.AUTH_USER_MODEL, verbose_name='Membre responsable')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.category', verbose_name='Catégorie')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.location', verbose_name='Périmètre de stockage')),
            ],
            options={
                'ordering': ['due_on', '-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(verbose_name='Compte rendu / justification')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='erp.workitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='inventorycampaign',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='erp.workitem'),
        ),
        migrations.AddField(
            model_name='cdcdossier',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cdc', to='erp.workitem'),
        ),
        migrations.AddConstraint(
            model_name='cdclot',
            constraint=models.UniqueConstraint(fields=('dossier', 'position'), name='erp_cdc_lot_position'),
        ),
        migrations.AddConstraint(
            model_name='cdcitem',
            constraint=models.UniqueConstraint(fields=('lot', 'source_key'), name='erp_cdc_item_source'),
        ),
        migrations.AddConstraint(
            model_name='cdcitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='erp_cdc_item_quantity'),
        ),
        migrations.AddConstraint(
            model_name='cdcitem',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_price__isnull', True), ('estimated_price__gte', 0), _connector='OR'), name='erp_cdc_estimate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cdcitem',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__isnull', True), models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), _connector='OR'), name='erp_cdc_tax_range'),
        ),
        migrations.AddConstraint(
            model_name='cdcrevision',
            constraint=models.UniqueConstraint(fields=('dossier', 'number'), name='erp_cdc_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='inventoryline',
            constraint=models.UniqueConstraint(fields=('campaign', 'container'), name='erp_inventory_container'),
        ),
        migrations.AddConstraint(
            model_name='inventoryline',
            constraint=models.CheckConstraint(condition=models.Q(('counted_quantity__isnull', True), ('counted_quantity__gte', 0), _connector='OR'), name='erp_inventory_count_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['article', 'status', 'expires_on'], name='erp_stocklo_article_949018_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.UniqueConstraint(fields=('article', 'manufacturer_lot', 'serial_number'), name='erp_lot_identity'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(('manufactured_on__isnull', True), ('expires_on__isnull', True), ('manufactured_on__lte', models.F('expires_on')), _connector='OR'), name='erp_lot_dates'),
        ),
        migrations.AddIndex(
            model_name='stockcontainer',
            index=models.Index(fields=['location', 'lot'], name='erp_stockco_locatio_f363b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockcontainer',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0), ('quantity__lte', Decimal('999999999999.999999')), ('reserved__gte', 0), ('reserved__lte', models.F('quantity'))), name='erp_container_balance'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['kind', 'created_at'], name='erp_stockmo_kind_9b03f0_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['request', 'created_at'], name='erp_stockmo_request_2a24bc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['container', 'created_at'], name='erp_stocken_contain_9a01eb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['location', 'created_at'], name='erp_stocken_locatio_2703f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta', 0), ('reserved_delta', 0), _negated=True), name='erp_entry_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='stockreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gt', 0)), name='erp_receipt_quantity'),
        ),
        migrations.AddConstraint(
            model_name='stockreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_quantity__isnull', True), ('ordered_quantity__gt', 0), _connector='OR'), name='erp_receipt_order_quantity'),
        ),
        migrations.AddConstraint(
            model_name='stockreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__isnull', True), ('unit_price__gte', 0), _connector='OR'), name='erp_receipt_price'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='erp_reservation_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['assignee', 'status', 'due_on'], name='erp_workite_assigne_180ce6_idx'),
        ),
    ]
