# Generated by Django 5.2.17 on 2026-09-21 13:33

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_commercial_document_defaults'),
        ('erp', '0004_cdcdossier_inventorycampaign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiologicalSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9._-]{0,31}$')], verbose_name='Code interne')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation française')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Désignation anglaise')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Désignation arabe')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('source_kind', models.CharField(choices=[('IBTIKAR', 'IBTIKAR'), ('LEGACY', 'Demande PLAGENOR'), ('MANUAL', 'Réception documentée'), ('ALIQUOT', 'Aliquot')], max_length=16)),
                ('source_key', models.CharField(blank=True, max_length=100)),
                ('source_fingerprint', models.CharField(blank=True, editable=False, max_length=64)),
                ('source_snapshot', models.JSONField(default=dict, editable=False)),
                ('sample_type', models.CharField(blank=True, max_length=160, verbose_name='Type d’échantillon')),
                ('matrix', models.CharField(blank=True, max_length=160, verbose_name='Matrice')),
                ('received_on', models.DateField(verbose_name='Date de réception')),
                ('collected_on', models.DateField(blank=True, null=True, verbose_name='Date de prélèvement')),
                ('concentration_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Concentration')),
                ('initial_quantity', models.DecimalField(decimal_places=6, editable=False, max_digits=18, verbose_name='Quantité initiale')),
                ('remaining_quantity', models.DecimalField(decimal_places=6, editable=False, max_digits=18, verbose_name='Quantité restante')),
                ('status', models.CharField(choices=[('STORED', 'Stocké'), ('OUT', 'Sorti du stockage'), ('QUARANTINE', 'Quarantaine'), ('EXHAUSTED', 'Épuisé'), ('SHIPPED', 'Expédié'), ('DESTROYED', 'Détruit')], default='STORED', max_length=12, verbose_name='État de l’échantillon')),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Température minimale de conservation (°C)')),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Température maximale de conservation (°C)')),
                ('preservation', models.CharField(blank=True, max_length=500, verbose_name='Conditions de conservation documentées')),
                ('freeze_thaw_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Seuil de cycles selon le protocole')),
                ('freeze_thaw_cycles', models.PositiveIntegerField(default=0, editable=False)),
                ('checked_out_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('thawed_during_checkout', models.BooleanField(default=False, editable=False)),
                ('out_of_storage_seconds', models.PositiveBigIntegerField(default=0, editable=False)),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
                ('concentration_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.unit', verbose_name='Unité de concentration')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biological_samples', to='erp.location')),
                ('origin_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_samples', to='core.request')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aliquots', to='erp.biologicalsample')),
                ('root_sample', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descendant_samples', to='erp.biologicalsample')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.unit', verbose_name='Unité de gestion')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('FAILURE', 'Panne'), ('TEMPERATURE', 'Excursion de température'), ('MAINTENANCE', 'Maintenance'), ('DEFROST', 'Dégivrage')], max_length=16, verbose_name='Type d’incident')),
                ('started_at', models.DateTimeField(verbose_name='Début de l’incident')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de l’incident')),
                ('description', models.TextField(verbose_name='Description et impact observé')),
                ('corrective_action', models.TextField(blank=True, verbose_name='Action corrective')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='erp.location')),
                ('work', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incident', to='erp.workitem')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StoragePosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9._-]{0,31}$')], verbose_name='Code interne')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation française')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Désignation anglaise')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Désignation arabe')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('row', models.PositiveSmallIntegerField(verbose_name='Ligne')),
                ('column', models.PositiveSmallIntegerField(verbose_name='Colonne')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='erp.location')),
            ],
            options={
                'ordering': ['row', 'column'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SampleEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('RECEIPT', 'Réception'), ('ALIQUOT', 'Aliquotage'), ('TRANSFER', 'Transfert'), ('CHECK_OUT', 'Sortie du stockage'), ('RETURN', 'Retour au stockage'), ('CONSUMPTION', 'Consommation analytique'), ('QUARANTINE', 'Mise en quarantaine'), ('RELEASE', 'Libération après contrôle'), ('SHIPMENT', 'Expédition'), ('DESTRUCTION', 'Destruction')], max_length=12)),
                ('quantity_delta', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('reason', models.CharField(max_length=500, verbose_name='Motif')),
                ('data', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.location')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_sample_events', to='core.request')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='erp.biologicalsample')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.location')),
                ('from_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.storageposition')),
                ('to_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.storageposition')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PositionReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('until', models.DateTimeField(verbose_name='Réservée jusqu’au')),
                ('reason', models.CharField(max_length=500, verbose_name='Motif')),
                ('active', models.BooleanField(default=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='erp.storageposition')),
            ],
        ),
        migrations.AddField(
            model_name='biologicalsample',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occupant', to='erp.storageposition'),
        ),
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measured_at', models.DateTimeField(verbose_name='Date et heure du relevé')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Température mesurée (°C)')),
                ('minimum_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('maximum_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('out_of_range', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('MANUAL', 'Relevé manuel'), ('IMPORT', 'Import contrôlé')], max_length=16)),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Observation')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='erp.storageincident')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temperature_readings', to='erp.location')),
            ],
            options={
                'ordering': ['-measured_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='storageincident',
            constraint=models.CheckConstraint(condition=models.Q(('resolved_at__isnull', True), ('resolved_at__gte', models.F('started_at')), _connector='OR'), name='erp_incident_chronology'),
        ),
        migrations.AddConstraint(
            model_name='storageposition',
            constraint=models.UniqueConstraint(fields=('location', 'row', 'column'), name='erp_storage_grid_position'),
        ),
        migrations.AddConstraint(
            model_name='storageposition',
            constraint=models.CheckConstraint(condition=models.Q(('column__gt', 0), ('row__gt', 0)), name='erp_storage_grid_positive'),
        ),
        migrations.AddIndex(
            model_name='sampleevent',
            index=models.Index(fields=['sample', 'created_at'], name='erp_samplee_sample__77a65f_idx'),
        ),
        migrations.AddIndex(
            model_name='sampleevent',
            index=models.Index(fields=['request', 'kind'], name='erp_samplee_request_b747a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='positionreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('position',), name='erp_active_position_reservation'),
        ),
        migrations.AddIndex(
            model_name='biologicalsample',
            index=models.Index(fields=['location', 'status'], name='erp_biologi_locatio_5b6fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='biologicalsample',
            index=models.Index(fields=['origin_request', 'source_kind'], name='erp_biologi_origin__529b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='biologicalsample',
            index=models.Index(fields=['root_sample', 'status'], name='erp_biologi_root_sa_b9bcd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='biologicalsample',
            constraint=models.UniqueConstraint(condition=models.Q(('origin_request__isnull', False)), fields=('origin_request', 'source_kind', 'source_key'), name='erp_sample_request_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='biologicalsample',
            constraint=models.CheckConstraint(condition=models.Q(('initial_quantity__gt', 0), ('initial_quantity__lte', Decimal('999999999999.999999')), ('remaining_quantity__gte', 0), ('remaining_quantity__lte', models.F('initial_quantity'))), name='erp_sample_quantity_bounds'),
        ),
        migrations.AddConstraint(
            model_name='biologicalsample',
            constraint=models.CheckConstraint(condition=models.Q(('collected_on__isnull', True), ('collected_on__lte', models.F('received_on')), _connector='OR'), name='erp_sample_collection_date'),
        ),
        migrations.AddConstraint(
            model_name='biologicalsample',
            constraint=models.CheckConstraint(condition=models.Q(('temperature_min__isnull', True), ('temperature_max__isnull', True), ('temperature_min__lte', models.F('temperature_max')), _connector='OR'), name='erp_sample_temperature_range'),
        ),
        migrations.AddConstraint(
            model_name='biologicalsample',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('concentration_unit__isnull', True), ('concentration_value__isnull', True)), models.Q(('concentration_unit__isnull', False), ('concentration_value__gte', 0), ('concentration_value__isnull', False)), _connector='OR'), name='erp_sample_concentration_pair'),
        ),
        migrations.AddConstraint(
            model_name='biologicalsample',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('pk')), _negated=True), name='erp_sample_not_own_parent'),
        ),
        migrations.AddIndex(
            model_name='temperaturereading',
            index=models.Index(fields=['location', 'measured_at'], name='erp_tempera_locatio_5c613c_idx'),
        ),
    ]
