# Generated by Django 5.2.17 on 2026-09-21 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_biologicalsample_storageincident_storageposition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalsample',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='cdcitem',
            name='article_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.CreateModel(
            name='StorageTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField(unique=True)),
                ('mapping', models.JSONField(default=list)),
                ('payload_hash', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=500, verbose_name='Motif du transfert collectif')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.location')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='erp.storageincident')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
