# Generated by Django 5.2.17 on 2026-09-21 14:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_commercial_document_defaults'),
        ('erp', '0006_alter_biologicalsample_source_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleevent',
            name='kind',
            field=models.CharField(choices=[('RECEIPT', 'Réception'), ('ALIQUOT', 'Aliquotage'), ('TRANSFER', 'Transfert'), ('CHECK_OUT', 'Sortie du stockage'), ('RETURN', 'Retour au stockage'), ('CONSUMPTION', 'Consommation analytique'), ('ANALYSIS', 'Analyse sans quantité biologique consommée'), ('QUARANTINE', 'Mise en quarantaine'), ('RELEASE', 'Libération après contrôle'), ('SHIPMENT', 'Expédition'), ('DESTRUCTION', 'Destruction')], max_length=12),
        ),
        migrations.CreateModel(
            name='ConsumptionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9._-]{0,31}$')], verbose_name='Code interne')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation française')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Désignation anglaise')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Désignation arabe')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('reference_samples', models.PositiveIntegerField(default=1, verbose_name='Nombre d’échantillons de référence')),
                ('protocol_reference', models.CharField(max_length=255, verbose_name='Protocole / SOP')),
                ('notes', models.TextField(blank=True, verbose_name='Précisions opérationnelles')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumption_profiles', to='core.service')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9._-]{0,31}$')], verbose_name='Code interne')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation française')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Désignation anglaise')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Désignation arabe')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('profile_snapshot', models.JSONField(default=dict, editable=False)),
                ('sample_count', models.PositiveIntegerField(verbose_name='Nombre d’échantillons')),
                ('planned_on', models.DateField(verbose_name='Date prévue')),
                ('incremental_demand', models.BooleanField(default=False, verbose_name='Activité supplémentaire non comprise dans le rythme habituel')),
                ('committed', models.BooleanField(default=False, verbose_name='Activité prévue confirmée par l’administration')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifié'), ('RESERVED', 'Stock réservé'), ('COMPLETED', 'Consommations confirmées'), ('CANCELLED', 'Annulé')], default='PLANNED', max_length=12)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_runs', to='core.request')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.consumptionprofile')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumptionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Quantité standard')),
                ('basis', models.CharField(choices=[('PROPORTIONAL', 'Proportionnel au nombre d’échantillons'), ('BATCH', 'Par série complète ou partielle')], max_length=16, verbose_name='Mode de calcul')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumption_rules', to='erp.article')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='erp.consumptionprofile')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.unit')),
            ],
            options={
                'ordering': ['article__code', 'basis'],
            },
        ),
        migrations.CreateModel(
            name='RunInput',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=100)),
                ('source_fingerprint', models.CharField(blank=True, max_length=64)),
                ('label', models.CharField(max_length=180)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inputs', to='erp.analysisrun')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_inputs', to='erp.biologicalsample')),
            ],
        ),
        migrations.CreateModel(
            name='RunOperation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField(unique=True)),
                ('kind', models.CharField(choices=[('RESERVE', 'Réserver'), ('CONFIRM', 'Confirmer les consommations'), ('CANCEL', 'Annuler'), ('COMMIT', 'Confirmer l’activité prévue')], max_length=12)),
                ('payload_hash', models.CharField(max_length=64)),
                ('data', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='erp.analysisrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunBiologyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='run_link', to='erp.sampleevent')),
                ('input', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='biology_event', to='erp.runinput')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.runoperation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunRequirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('article_snapshot', models.JSONField(default=dict)),
                ('calculation', models.JSONField(default=list)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.article')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='erp.analysisrun')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.unit')),
            ],
            options={
                'ordering': ['article__code'],
            },
        ),
        migrations.CreateModel(
            name='RunConsumption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytical_consumptions', to='erp.stockcontainer')),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='analytical_consumption', to='erp.stockmovement')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='erp.analysisrun')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='erp.runoperation')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='erp.runrequirement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='run_allocation', to='erp.stockreservation')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='erp.runoperation')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='erp.runrequirement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='consumptionprofile',
            constraint=models.CheckConstraint(condition=models.Q(('reference_samples__gt', 0)), name='erp_recipe_reference_samples'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['planned_on', 'status'], name='erp_analysi_planned_bab7da_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['request', 'status'], name='erp_analysi_request_6a8db6_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.CheckConstraint(condition=models.Q(('sample_count__gt', 0)), name='erp_run_sample_count'),
        ),
        migrations.AddConstraint(
            model_name='consumptionrule',
            constraint=models.UniqueConstraint(fields=('profile', 'article', 'basis'), name='erp_recipe_article_basis'),
        ),
        migrations.AddConstraint(
            model_name='consumptionrule',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='erp_recipe_quantity'),
        ),
        migrations.AddConstraint(
            model_name='runinput',
            constraint=models.UniqueConstraint(fields=('run', 'source_key'), name='erp_run_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='runinput',
            constraint=models.UniqueConstraint(condition=models.Q(('sample__isnull', False)), fields=('run', 'sample'), name='erp_run_sample_unique'),
        ),
        migrations.AddConstraint(
            model_name='runrequirement',
            constraint=models.UniqueConstraint(fields=('run', 'article'), name='erp_run_article_requirement'),
        ),
        migrations.AddConstraint(
            model_name='runrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='erp_run_requirement_positive'),
        ),
    ]
