# Generated by Django 5.2.17 on 2026-09-21 17:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_commercial_document_defaults'),
        ('erp', '0008_operational_history_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='kind',
            field=models.CharField(choices=[('INVENTORY', 'Inventaire physique'), ('CDC', 'Cahier des charges'), ('RECEIPT', 'Contrôle de réception'), ('TEMPERATURE', 'Relevé de température'), ('PLAN', 'Plan d’approvisionnement'), ('CONTROL', 'Contrôle opérationnel'), ('ANALYSIS', 'Activité analytique'), ('MAINTENANCE', 'Maintenance'), ('QUALITY', 'Contrôle qualité'), ('TRAINING', 'Formation'), ('MEETING', 'Réunion'), ('OTHER', 'Autre activité')], max_length=16, verbose_name='Type de tâche'),
        ),
        migrations.CreateModel(
            name='PlanningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9._-]{0,31}$')], verbose_name='Code interne')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation française')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Désignation anglaise')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Désignation arabe')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('kind', models.CharField(choices=[('EQUIPMENT', 'Équipement'), ('ROOM', 'Salle'), ('OTHER', 'Autre ressource')], max_length=12, verbose_name='Type de ressource')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='Numéro de série')),
                ('instructions', models.TextField(blank=True, verbose_name='Consignes de réservation')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.location')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(verbose_name='Début d’indisponibilité')),
                ('ends_at', models.DateTimeField(verbose_name='Fin d’indisponibilité')),
                ('reason', models.CharField(max_length=500, verbose_name='Motif')),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_unavailability', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unavailability', to='erp.planningresource')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(verbose_name='Début prévu')),
                ('ends_at', models.DateTimeField(verbose_name='Fin prévue')),
                ('resource_check_note', models.TextField(blank=True, verbose_name='Vérification des ressources')),
                ('resources_checked_at', models.DateTimeField(blank=True, null=True)),
                ('creation_key', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('creation_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('actual_started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('actual_finished_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_activities', to='core.request')),
                ('resources_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='erp.analysisrun')),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='erp.workitem')),
                ('resources', models.ManyToManyField(blank=True, related_name='schedules', to='erp.planningresource')),
            ],
            options={
                'ordering': ['starts_at', 'work__title'],
            },
        ),
        migrations.CreateModel(
            name='ActivityDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='erp.workitem')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prerequisites', to='erp.workitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('work', 'prerequisite'), name='erp_unique_activity_dependency'), models.CheckConstraint(condition=models.Q(('work', models.F('prerequisite')), _negated=True), name='erp_dependency_not_self')],
            },
        ),
        migrations.AddConstraint(
            model_name='planningresource',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'ROOM'), ('location__isnull', False)), fields=('location',), name='erp_one_planning_room'),
        ),
        migrations.AddIndex(
            model_name='availabilityblock',
            index=models.Index(fields=['starts_at', 'ends_at', 'active'], name='erp_availab_starts__e7baa0_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityblock',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='erp_unavailability_interval'),
        ),
        migrations.AddConstraint(
            model_name='availabilityblock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('member__isnull', True), ('resource__isnull', False)), models.Q(('member__isnull', False), ('resource__isnull', True)), _connector='OR'), name='erp_unavailability_one_target'),
        ),
        migrations.AddIndex(
            model_name='activityschedule',
            index=models.Index(fields=['starts_at', 'ends_at'], name='erp_activit_starts__d6e3fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityschedule',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='erp_activity_positive_interval'),
        ),
    ]
