# Generated by Django 5.2.17 on 2026-09-21 20:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_alter_workitem_kind_planningresource_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastObservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of', models.DateField()),
                ('input_data', models.JSONField()),
                ('result', models.JSONField()),
                ('sha256', models.CharField(max_length=64)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='erp.article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcurementPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=90, unique=True, verbose_name='Référence du plan')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Année du plan')),
                ('starts_on', models.DateField(verbose_name='Début de la période')),
                ('ends_on', models.DateField(verbose_name='Fin de la période')),
                ('revision_number', models.PositiveIntegerField(default=0, editable=False)),
                ('cdc', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_plan', to='erp.cdcdossier')),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_plan', to='erp.workitem')),
            ],
            options={
                'ordering': ['-year', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article_snapshot', models.JSONField(default=dict, editable=False)),
                ('purchase_factor', models.DecimalField(decimal_places=9, editable=False, max_digits=24)),
                ('proposed_quantity', models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=18, null=True)),
                ('retained_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Quantité retenue en unité d’achat')),
                ('included', models.BooleanField(default=True, verbose_name='Retenir cet article')),
                ('lot_name', models.CharField(max_length=180, verbose_name='Lot d’achat')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Haute'), ('MEDIUM', 'Moyenne'), ('LOW', 'Faible')], max_length=10, verbose_name='Priorité')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Prix unitaire estimé hors taxes')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux de taxe (%)')),
                ('currency', models.CharField(default='DZD', max_length=3, verbose_name='Devise')),
                ('price_source', models.CharField(blank=True, max_length=500, verbose_name='Source du prix')),
                ('decision_reason', models.CharField(blank=True, max_length=500, verbose_name='Justification de la décision')),
                ('reviewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.article', verbose_name='Article du catalogue commun')),
                ('forecast', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.forecastobservation')),
                ('purchase_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.unit')),
                ('reviewed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.party')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='erp.procurementplan')),
            ],
            options={
                'ordering': ['lot_name', 'article__code'],
            },
        ),
        migrations.AddField(
            model_name='forecastobservation',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='erp.procurementplan'),
        ),
        migrations.CreateModel(
            name='ProcurementRevision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('sha256', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='erp.procurementplan')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='procurementplan',
            name='approved_revision',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_plan', to='erp.procurementrevision'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=120, unique=True, verbose_name='Référence commande / marché')),
                ('ordered_on', models.DateField(verbose_name='Date de commande')),
                ('expected_on', models.DateField(verbose_name='Livraison confirmée pour le')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('CONFIRMED', 'Commande confirmée'), ('PARTIAL', 'Réception partielle'), ('RECEIVED', 'Réception complète'), ('CANCELLED', 'Solde annulé')], default='DRAFT', max_length=12)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='erp.procurementplan')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.party', verbose_name='Fournisseur')),
            ],
            options={
                'ordering': ['-ordered_on', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article_snapshot', models.JSONField(default=dict, editable=False)),
                ('factor', models.DecimalField(decimal_places=9, editable=False, max_digits=24)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Quantité commandée')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Prix unitaire commandé HT')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de taxe (%)')),
                ('currency', models.CharField(default='DZD', max_length=3)),
                ('variance_reason', models.CharField(blank=True, max_length=500, verbose_name='Justification de l’écart au plan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='erp.purchaseorder')),
                ('plan_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='erp.procurementline')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.unit')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceiptLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('actual_unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expected_delivery_snapshot', models.DateField()),
                ('variance_reason', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='erp.purchaseorderline')),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_delivery', to='erp.stockreceipt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='procurementline',
            constraint=models.UniqueConstraint(fields=('plan', 'article'), name='erp_plan_unique_article'),
        ),
        migrations.AddConstraint(
            model_name='procurementline',
            constraint=models.CheckConstraint(condition=models.Q(('retained_quantity__isnull', True), models.Q(('retained_quantity__gte', 0), ('retained_quantity__lte', Decimal('999999999999.999999'))), _connector='OR'), name='erp_plan_retained_quantity'),
        ),
        migrations.AddConstraint(
            model_name='procurementline',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__isnull', True), models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), _connector='OR'), name='erp_plan_tax_rate'),
        ),
        migrations.AddConstraint(
            model_name='procurementline',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_price__isnull', True), ('estimated_price__gte', 0), _connector='OR'), name='erp_plan_estimated_price'),
        ),
        migrations.AddConstraint(
            model_name='procurementrevision',
            constraint=models.UniqueConstraint(fields=('plan', 'number'), name='erp_plan_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='procurementplan',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='erp_procurement_plan_period'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('expected_on__gte', models.F('ordered_on'))), name='erp_order_delivery_dates'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('order', 'plan_line'), name='erp_order_plan_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('quantity__lte', Decimal('999999999999.999999'))), name='erp_order_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='erp_order_nonnegative_price'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='erp_order_tax_rate'),
        ),
    ]
