# Generated by Django 5.2.17 on 2026-09-21 20:36

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_procurement_integrity_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='procurementline',
            name='erp_plan_estimated_price',
        ),
        migrations.RemoveConstraint(
            model_name='purchaseorderline',
            name='erp_order_nonnegative_price',
        ),
        migrations.AddConstraint(
            model_name='procurementline',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_price__isnull', True), models.Q(('estimated_price__gte', 0), ('estimated_price__lte', Decimal('9999999999999999.99'))), _connector='OR'), name='erp_plan_estimated_price'),
        ),
        migrations.AddConstraint(
            model_name='procurementline',
            constraint=models.CheckConstraint(condition=models.Q(('proposed_quantity__isnull', True), models.Q(('proposed_quantity__gte', 0), ('proposed_quantity__lte', Decimal('999999999999.999999'))), _connector='OR'), name='erp_plan_proposed_quantity'),
        ),
        migrations.AddConstraint(
            model_name='procurementline',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_factor__gt', 0), ('purchase_factor__lte', Decimal('999999999999999.999999999'))), name='erp_plan_purchase_factor'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0), ('unit_price__lte', Decimal('9999999999999999.99'))), name='erp_order_nonnegative_price'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('factor__gt', 0), ('factor__lte', Decimal('999999999999999.999999999'))), name='erp_order_factor'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceiptlink',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_quantity__gt', 0), ('purchase_quantity__lte', Decimal('999999999999.999999'))), name='erp_purchase_receipt_quantity'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceiptlink',
            constraint=models.CheckConstraint(condition=models.Q(('actual_unit_price__gte', 0), ('actual_unit_price__lte', Decimal('9999999999999999.99'))), name='erp_purchase_receipt_price'),
        ),
    ]
