# Generated by Django 5.2.17 on 2026-09-21 20:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_remove_procurementline_erp_plan_estimated_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='minimum_order_quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Commande minimale (unité d’achat)'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_order_quantity__gte', 0), ('minimum_order_quantity__lte', Decimal('999999999999.999999'))), name='erp_min_order_quantity'),
        ),
    ]
