# Generated by Django 5.2.17 on 2026-09-21 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_article_minimum_order_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creation_key', models.UUIDField(editable=False, unique=True)),
                ('creation_hash', models.CharField(editable=False, max_length=64)),
                ('kind', models.CharField(choices=[('CATALOG', 'Catalogue des articles'), ('INITIAL', 'Stock physique initial'), ('RECEIPTS', 'Réceptions de stock'), ('LOCATIONS', 'Emplacements'), ('SAMPLES', 'Échantillons'), ('PRICES', 'Observations de prix'), ('PLAN', 'Articles d’un plan annuel'), ('TEMPERATURE', 'Relevés de température')], max_length=16, verbose_name='Domaine d’import')),
                ('filename', models.CharField(max_length=180)),
                ('sha256', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=list)),
                ('baselines', models.JSONField(default=list)),
                ('report', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PREVIEW', 'Aperçu à examiner'), ('APPLIED', 'Import appliqué'), ('CANCELLED', 'Import abandonné')], default='PREVIEW', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=500, verbose_name='Justification de l’import')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_imports', to=settings.AUTH_USER_MODEL)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='erp.procurementplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'status', 'created_at'], name='erp_importb_actor_i_24bd27_idx')],
            },
        ),
    ]
