# Generated by Django 5.2.17 on 2026-09-21 21:17

import django.db.models.deletion
import erp.models.alerts
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_import_history_guards'),
        ('notifications', '0003_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='PLAGENOR', editable=False, max_length=32, unique=True)),
                ('expiry_days', models.JSONField(default=erp.models.alerts.expiry_windows, verbose_name='Seuils de péremption (jours)')),
                ('dormant_days', models.PositiveIntegerField(default=180, verbose_name='Absence de consommation (jours)')),
                ('receipt_pending_days', models.PositiveIntegerField(default=2, verbose_name='Réception en attente depuis (jours)')),
                ('occupancy_percent', models.DecimalField(decimal_places=2, default=Decimal('90'), max_digits=5, verbose_name='Occupation à signaler (%)')),
                ('overstock_multiplier', models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=6, verbose_name='Surstock : multiple du stock cible')),
                ('digest_enabled', models.BooleanField(default=True, verbose_name='Activer la synthèse quotidienne dans les notifications')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('occupancy_percent__gt', 0), ('occupancy_percent__lte', 100)), name='erp_alert_occupancy_percentage'), models.CheckConstraint(condition=models.Q(('overstock_multiplier__gte', 1), ('overstock_multiplier__lte', 100)), name='erp_alert_overstock_multiple')],
            },
        ),
        migrations.CreateModel(
            name='AlertAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signature', models.CharField(max_length=64)),
                ('data', models.JSONField()),
                ('reason', models.CharField(max_length=500, verbose_name='Action engagée / observation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alert_acknowledgements', to='erp.workitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'signature'), name='erp_alert_ack_unique')],
            },
        ),
        migrations.CreateModel(
            name='AlertDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateField()),
                ('counts', models.JSONField()),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'day'), name='erp_daily_alert_digest_unique')],
            },
        ),
    ]
