# Generated by Django 5.2.17 on 2026-09-21 21:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_alertpolicy_alertacknowledgement_alertdigest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.TextField(verbose_name='Classification et mentions relevées dans la FDS')),
                ('signal_word', models.CharField(blank=True, choices=[('', '—'), ('DANGER', 'Danger'), ('WARNING', 'Attention')], max_length=8, verbose_name='Mention d’avertissement documentée')),
                ('handling', models.TextField(blank=True, verbose_name='Précautions et restrictions documentées')),
                ('source_reference', models.CharField(max_length=500, verbose_name='FDS / source officielle et version')),
                ('reviewed_on', models.DateField(verbose_name='Date de vérification de la source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HazardTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9._-]{0,31}$')], verbose_name='Code interne')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation française')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Désignation anglaise')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Désignation arabe')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('ghs_code', models.CharField(blank=True, choices=[('', '—'), ('GHS01', 'GHS01'), ('GHS02', 'GHS02'), ('GHS03', 'GHS03'), ('GHS04', 'GHS04'), ('GHS05', 'GHS05'), ('GHS06', 'GHS06'), ('GHS07', 'GHS07'), ('GHS08', 'GHS08'), ('GHS09', 'GHS09')], max_length=5, verbose_name='Pictogramme indiqué sur la FDS')),
                ('description', models.TextField(blank=True, verbose_name='Description documentée')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('SDS', 'Fiche de données de sécurité'), ('CERTIFICATE', 'Certificat / contrôle'), ('PROTOCOL', 'Protocole / SOP'), ('EVIDENCE', 'Justificatif / preuve'), ('OTHER', 'Autre document')], max_length=12, verbose_name='Type de document')),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé du document')),
                ('financial', models.BooleanField(default=False, verbose_name='Contient des informations financières restreintes')),
                ('original_name', models.CharField(max_length=180)),
                ('extension', models.CharField(max_length=6)),
                ('content', models.BinaryField()),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('size', models.PositiveIntegerField(editable=False)),
                ('documented_on', models.DateField(blank=True, null=True, verbose_name='Date du document')),
                ('source', models.CharField(max_length=500, verbose_name='Origine / référence documentaire')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageSafetyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('PROHIBITED', 'Danger interdit dans cet emplacement'), ('INCOMPATIBLE', 'Deux groupes ne peuvent pas être stockés ensemble')], max_length=16, verbose_name='Type de règle')),
                ('blocking', models.BooleanField(default=True, verbose_name='Bloquer une réception ou un transfert incompatible')),
                ('active', models.BooleanField(default=True, verbose_name='Règle active')),
                ('reference', models.CharField(max_length=500, verbose_name='Justification / source de la règle')),
            ],
        ),
        migrations.AddField(
            model_name='internalpreparation',
            name='concentration_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.unit', verbose_name='Unité de concentration'),
        ),
        migrations.AddField(
            model_name='internalpreparation',
            name='concentration_value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Valeur de concentration'),
        ),
        migrations.AddConstraint(
            model_name='internalpreparation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('concentration_unit__isnull', True), ('concentration_value__isnull', True)), models.Q(('concentration_unit__isnull', False), ('concentration_value__gte', 0), ('concentration_value__isnull', False), ('concentration_value__lte', Decimal('999999999999.999999'))), _connector='OR'), name='erp_preparation_concentration_pair'),
        ),
        migrations.AddField(
            model_name='chemicalprofile',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='chemical_profile', to='erp.article'),
        ),
        migrations.AddField(
            model_name='chemicalprofile',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chemicalprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='chemical_profiles', to='erp.hazardtag'),
        ),
        migrations.AddField(
            model_name='resourcedocument',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcedocument',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_documents', to='erp.article'),
        ),
        migrations.AddField(
            model_name='resourcedocument',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_documents', to='erp.purchaseorder'),
        ),
        migrations.AddField(
            model_name='resourcedocument',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_documents', to='erp.stockreceipt'),
        ),
        migrations.AddField(
            model_name='resourcedocument',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_documents', to='erp.biologicalsample'),
        ),
        migrations.AddField(
            model_name='resourcedocument',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement', to='erp.resourcedocument'),
        ),
        migrations.AddField(
            model_name='resourcedocument',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_documents', to='erp.workitem'),
        ),
        migrations.AddField(
            model_name='chemicalprofile',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemical_profiles', to='erp.resourcedocument'),
        ),
        migrations.AddField(
            model_name='storagesafetyrule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagesafetyrule',
            name='first_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.hazardtag', verbose_name='Premier groupe de danger'),
        ),
        migrations.AddField(
            model_name='storagesafetyrule',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safety_rules', to='erp.location'),
        ),
        migrations.AddField(
            model_name='storagesafetyrule',
            name='second_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.hazardtag', verbose_name='Groupe incompatible'),
        ),
        migrations.AddConstraint(
            model_name='resourcedocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('article__isnull', False), ('order__isnull', True), ('receipt__isnull', True), ('sample__isnull', True), ('work__isnull', True)), models.Q(('article__isnull', True), ('order__isnull', True), ('receipt__isnull', False), ('sample__isnull', True), ('work__isnull', True)), models.Q(('article__isnull', True), ('order__isnull', True), ('receipt__isnull', True), ('sample__isnull', True), ('work__isnull', False)), models.Q(('article__isnull', True), ('order__isnull', True), ('receipt__isnull', True), ('sample__isnull', False), ('work__isnull', True)), models.Q(('article__isnull', True), ('order__isnull', False), ('receipt__isnull', True), ('sample__isnull', True), ('work__isnull', True)), _connector='OR'), name='erp_resource_document_target'),
        ),
        migrations.AddConstraint(
            model_name='storagesafetyrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mode', 'PROHIBITED'), ('second_tag__isnull', True)), models.Q(('mode', 'INCOMPATIBLE'), ('second_tag__isnull', False)), _connector='OR'), name='erp_storage_rule_pair'),
        ),
    ]
