# Generated by Django 5.2.17 on 2026-09-24 00:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_resource_evidence_immutable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cdclot',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Lot retenu'),
        ),
        migrations.CreateModel(
            name='CdcWorkbookPreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_version', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=180)),
                ('payload', models.JSONField()),
                ('import_prices', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('applied_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.cdcrevision')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workbook_imports', to='erp.cdcdossier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
