# Generated by Django 5.2.17 on 2026-09-26 01:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_cdc_procurement_history_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyInventoryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_key', models.CharField(max_length=180, unique=True, verbose_name='Clé source')),
                ('source_file', models.CharField(max_length=255, verbose_name='Fichier source')),
                ('source_section', models.CharField(blank=True, max_length=120, verbose_name='Feuille / section source')),
                ('source_row', models.CharField(blank=True, max_length=64, verbose_name='Ligne source')),
                ('kind', models.CharField(choices=[('EQUIPMENT', 'Équipement'), ('CHEMICAL', 'Produit chimique'), ('CONSUMABLE', 'Consommable'), ('REAGENT', 'Réactif')], max_length=16, verbose_name='Nature')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='Empreinte des données source')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Données source originales')),
                ('resolution', models.CharField(choices=[('IMPORTED', 'Importé'), ('REUSED', 'Rattaché à un existant'), ('REVIEW', 'À vérifier'), ('SKIPPED', 'Non importé')], max_length=12, verbose_name='Résolution')),
                ('entity_type', models.CharField(blank=True, max_length=64, verbose_name='Type d’objet PLAGENOR')),
                ('entity_id', models.UUIDField(blank=True, null=True, verbose_name='Objet PLAGENOR')),
                ('note', models.TextField(blank=True, verbose_name='Observation de migration')),
            ],
            options={
                'ordering': ['source_file', 'source_section', 'source_row', 'source_key'],
                'indexes': [models.Index(fields=['kind', 'resolution'], name='erp_legacyi_kind_158029_idx'), models.Index(fields=['entity_type', 'entity_id'], name='erp_legacyi_entity__882d23_idx')],
            },
        ),
    ]
