# Generated by Django 5.2.17 on 2026-09-25 23:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_cdc_procurement_history_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningresource',
            name='inventory_status',
            field=models.CharField(choices=[('UNVERIFIED', 'À vérifier'), ('IN_SERVICE', 'En service'), ('MAINTENANCE', 'Maintenance'), ('OUT_OF_SERVICE', 'Hors service'), ('DECOMMISSIONED', 'Réformé')], default='IN_SERVICE', max_length=18, verbose_name='État inventaire'),
        ),
        migrations.AddField(
            model_name='planningresource',
            name='manufacturer_reference',
            field=models.CharField(blank=True, max_length=120, verbose_name='Référence fabricant'),
        ),
        migrations.AddField(
            model_name='planningresource',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Modèle'),
        ),
        migrations.AddField(
            model_name='planningresource',
            name='source_snapshot',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.CreateModel(
            name='InventorySourceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_kind', models.CharField(choices=[('WORKBOOK', 'Classeur inventaire'), ('ROOM_LIST', 'Fiche de salle')], max_length=16)),
                ('domain', models.CharField(choices=[('EQUIPMENT', 'Équipement'), ('CHEMICAL', 'Produit chimique'), ('CONSUMABLE', 'Consommable'), ('REAGENT', 'Réactif')], max_length=16)),
                ('source_file', models.CharField(max_length=255)),
                ('source_sha256', models.CharField(max_length=64)),
                ('source_sheet', models.CharField(blank=True, max_length=180)),
                ('source_row', models.PositiveIntegerField()),
                ('identity_key', models.CharField(db_index=True, max_length=64)),
                ('raw_data', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('IMPORTED', 'Importé'), ('ENRICHED', 'Enrichi'), ('NEEDS_REVIEW', 'À vérifier'), ('SKIPPED_DUPLICATE', 'Doublon source conservé')], default='NEEDS_REVIEW', max_length=20)),
                ('target_model', models.CharField(blank=True, max_length=64)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['source_file', 'source_sheet', 'source_row', 'id'],
                'indexes': [models.Index(fields=['domain', 'status'], name='erp_invento_domain_6185ce_idx'), models.Index(fields=['target_model', 'target_id'], name='erp_invento_target__0a6341_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_sha256', 'source_file', 'source_sheet', 'source_row', 'domain'), name='erp_inventory_source_identity')],
            },
        ),
    ]
