# Generated by Django 5.2.17 on 2026-09-26 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_legacy_inventory_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInventorySource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_designation', models.CharField(blank=True, max_length=255, verbose_name='Désignation source')),
                ('model', models.CharField(blank=True, max_length=255, verbose_name='Modèle')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Référence')),
                ('source_serial_number', models.CharField(blank=True, max_length=120, verbose_name='Numéro de série source')),
                ('source_quantity', models.PositiveIntegerField(verbose_name='Quantité déclarée dans la source')),
                ('source_file', models.CharField(max_length=255, verbose_name='Fichier source')),
                ('source_row', models.CharField(blank=True, max_length=64, verbose_name='Ligne source')),
                ('source_room', models.CharField(blank=True, max_length=32, verbose_name='Salle source')),
                ('source_fingerprint', models.CharField(max_length=64, verbose_name='Empreinte source')),
                ('resource', models.ForeignKey(limit_choices_to={'kind': 'EQUIPMENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_sources', to='erp.planningresource', verbose_name='Équipement')),
                ('source_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_inventory_source', to='erp.legacyinventoryrecord', verbose_name='Ligne source de l’inventaire')),
            ],
            options={
                'indexes': [models.Index(fields=['source_file', 'source_row'], name='erp_equipme_source__e6e6c6_idx'), models.Index(fields=['source_room'], name='erp_equipme_source__a3c16f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_quantity__gte', 1)), name='erp_equipment_inventory_source_qty_positive')],
            },
        ),
    ]
