# Generated by Django 5.2.17 on 2026-10-09 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_inventory_source_integrity_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CdcReusePreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_version', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('reason', models.CharField(max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('applied_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.cdcrevision')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reuse_previews', to='erp.cdcdossier')),
                ('source_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.cdcrevision')),
                ('target_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.cdclot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
