# Generated by Django 5.2.17 on 2026-10-10 09:31

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_cdcreusepreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.UUIDField(editable=False, unique=True)),
                ('kind', models.CharField(choices=[('CATALOG', 'Catalogue des articles'), ('INITIAL', 'Stock physique initial'), ('RECEIPTS', 'Réceptions de stock'), ('LOCATIONS', 'Emplacements'), ('SAMPLES', 'Échantillons'), ('PRICES', 'Observations de prix'), ('PLAN', 'Articles d’un plan annuel'), ('TEMPERATURE', 'Relevés de température')], max_length=16)),
                ('filename', models.CharField(max_length=180)),
                ('sha256', models.CharField(max_length=64)),
                ('matrix', models.JSONField(default=list)),
                ('choices', models.JSONField(default=dict)),
                ('reason', models.CharField(max_length=500)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockDispatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('mode', models.CharField(choices=[('EXIT', 'Sortie définitive'), ('INTERNAL', 'Transfert interne')], max_length=8, verbose_name='Mode de distribution')),
                ('beneficiary', models.CharField(max_length=255, verbose_name='Laboratoire / bénéficiaire')),
                ('distributed_on', models.DateField(verbose_name='Date de distribution')),
                ('reason', models.CharField(max_length=500, verbose_name='Motif')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockDispatchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('snapshot', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='StockReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('returned_on', models.DateField(verbose_name='Date de retour')),
                ('condition', models.CharField(max_length=255, verbose_name='État au retour')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='brand',
            field=models.CharField(blank=True, max_length=120, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='article',
            name='pack_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Quantité par conditionnement'),
        ),
        migrations.AddField(
            model_name='article',
            name='supplier_reference',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Référence fournisseur'),
        ),
        migrations.AddField(
            model_name='stockcontainer',
            name='fifo_received_on',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Date de réception initiale'),
        ),
        migrations.AddField(
            model_name='stockcontainer',
            name='source_container',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_containers', to='erp.stockcontainer'),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='delivery_reference',
            field=models.CharField(blank=True, max_length=120, verbose_name='Bon de livraison'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('pack_quantity__isnull', True), models.Q(('pack_quantity__gt', 0), ('pack_quantity__lte', Decimal('999999999999.999999'))), _connector='OR'), name='erp_article_pack_positive'),
        ),
        migrations.AddField(
            model_name='importmapping',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importmapping',
            name='batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.importbatch'),
        ),
        migrations.AddField(
            model_name='importmapping',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.procurementplan'),
        ),
        migrations.AddField(
            model_name='stockdispatch',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockdispatch',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.location'),
        ),
        migrations.AddField(
            model_name='stockdispatchline',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_lines', to='erp.stockcontainer'),
        ),
        migrations.AddField(
            model_name='stockdispatchline',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='erp.stockdispatch'),
        ),
        migrations.AddField(
            model_name='stockdispatchline',
            name='movement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_line', to='erp.stockmovement'),
        ),
        migrations.AddField(
            model_name='stockreturn',
            name='container',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_return', to='erp.stockcontainer'),
        ),
        migrations.AddField(
            model_name='stockreturn',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='erp.stockdispatchline'),
        ),
        migrations.AddField(
            model_name='stockreturn',
            name='movement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_return', to='erp.stockmovement'),
        ),
        migrations.AddConstraint(
            model_name='stockdispatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('destination__isnull', True), ('mode', 'EXIT')), models.Q(('destination__isnull', False), ('mode', 'INTERNAL')), _connector='OR'), name='erp_dispatch_destination'),
        ),
        migrations.AddConstraint(
            model_name='stockdispatchline',
            constraint=models.UniqueConstraint(fields=('dispatch', 'container'), name='erp_dispatch_container'),
        ),
        migrations.AddConstraint(
            model_name='stockdispatchline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='erp_dispatch_quantity'),
        ),
        migrations.AddConstraint(
            model_name='stockreturn',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='erp_return_quantity'),
        ),
    ]
