# Generated by Django 5.2.17 on 2026-10-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0031_distribution_history_guards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importmapping',
            name='choices',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
