# Generated by Django 5.1 on 2026-03-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ibtikar_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Identifiant IBTIKAR'),
        ),
    ]
