# Generated by Django 5.1 on 2026-05-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Suivre la configuration du navigateur"),
                    ("fr", "Français"),
                    ("en", "English"),
                    ("ar", "العربية"),
                ],
                default="",
                help_text="Laisser vide pour utiliser la langue du navigateur.",
                max_length=5,
                verbose_name="Langue préférée",
            ),
        ),
    ]
