# Generated by Django 5.1.7 on 2026-03-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_level_other',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Autre niveau (à préciser)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_level',
            field=models.CharField(blank=True, choices=[('phd_student', 'PhD Student / Doctorant'), ('phd_intern', 'PhD Intern / Stagiaire Doctorant'), ('master', "Master's Student / Étudiant en Master"), ('analyst', 'Analyst / Analyste'), ('intern', 'Intern / Stagiaire'), ('lecturer', 'Lecturer / Enseignant-Chercheur'), ('other', 'Other / Autre')], default='', max_length=50),
        ),
    ]
