# Generated by Django 5.1 on 2026-05-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="category_ar",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="technique",
            name="category_en",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="technique",
            name="category_fr",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="technique",
            name="name_ar",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="technique",
            name="name_en",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="technique",
            name="name_fr",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
