# Generated by Django 5.1.7 on 2026-03-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_student_level_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='last_milestone_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='milestone_count',
            field=models.IntegerField(default=0),
        ),
    ]
