# Generated by Django 5.1 on 2026-06-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_gender_user_wilaya"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ibtikar_balance_declared_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Dernière mise à jour du solde IBTIKAR",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ibtikar_declared_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Solde IBTIKAR déclaré (DA)",
            ),
        ),
    ]
