# Generated by Django 5.1.7 on 2026-04-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='laboratory',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Laboratory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('etudiant_doctorant', 'Étudiant/Doctorant'), ('chercheur', 'Chercheur'), ('mca', 'MCA'), ('mcb', 'MCB'), ('professeur', 'Professeur'), ('ingenieur', 'Ingénieur'), ('technicien', 'Technicien'), ('autre', 'Autre')], default='', max_length=50, verbose_name='Position / Fonction'),
        ),
    ]
