# Generated by Django 5.1 on 2026-04-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_laboratory_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('doctorant', 'Doctorant(e) / PhD Student'), ('etudiant_licence', 'Étudiant(e) en fin de cycle — Licence'), ('etudiant_master_ingenieur', 'Étudiant(e) en fin de cycle — Master / Ingénieur'), ('academique', 'Accadémique / Academic'), ('industriel', 'Industriel / Industrial'), ('hospitalier', 'Hospitalier / Hospital'), ('independant', 'Indépendant / Independent'), ('autre', 'Autre / Other'), ('chercheur', 'Chercheur'), ('mca', 'MCA'), ('mcb', 'MCB'), ('professeur', 'Professeur'), ('ingenieur', 'Ingénieur'), ('technicien', 'Technicien'), ('doctorant', 'Doctorant(e)')], default='', max_length=50, verbose_name='Position / Fonction'),
        ),
    ]
