# Generated by Django 5.1 on 2026-04-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_update_position_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='milestone_history',
            field=models.JSONField(blank=True, default=list, help_text='History of milestones achieved with dates and rewards'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='milestone_level',
            field=models.IntegerField(default=1, help_text='Current reward cycle level (1=first 1000pts, 2=second 1000pts, etc.)'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='reward_points',
            field=models.IntegerField(default=0, help_text='Points accumulated in current reward cycle (resets at 1000)'),
        ),
    ]
