# Generated by Django 5.2.15 on 2026-07-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_country_user_organization_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="totp_enabled",
            field=models.BooleanField(default=False, verbose_name="2FA activé"),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
