# Generated by Django 5.1 on 2026-04-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_reward_fields_to_memberprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, default='', help_text='Faculty or department within the university', max_length=200, verbose_name='Faculté / Faculty'),
        ),
        migrations.AddField(
            model_name='user',
            name='research_team',
            field=models.CharField(blank=True, default='', help_text='Research team or laboratory unit', max_length=200, verbose_name='Équipe de recherche / Research Team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('doctorant', 'Doctorant(e) / PhD Student'), ('etudiant_licence', 'Étudiant(e) en fin de cycle — Licence'), ('etudiant_master_ingenieur', 'Étudiant(e) en fin de cycle — Master / Ingénieur'), ('director', 'Directeur / Director'), ('manager', 'Responsable / Manager'), ('lab_technician', 'Technicien de laboratoire / Lab Technician'), ('researcher', 'Chercheur / Researcher'), ('engineer', 'Ingénieur / Engineer'), ('other', 'Autre / Other'), ('chercheur', 'Chercheur'), ('mca', 'MCA'), ('mcb', 'MCB'), ('professeur', 'Professeur'), ('ingenieur', 'Ingénieur'), ('technicien', 'Technicien'), ('doctorant', 'Doctorant(e)')], default='', max_length=50, verbose_name='Position / Fonction'),
        ),
    ]
