# Generated by Django 5.2.17 on 2026-08-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_totp_enabled_user_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
