# Generated by Django 5.1 on 2026-04-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_address_user_country_user_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='badge_level',
            field=models.IntegerField(default=0, help_text='Badge level: 0=none, 1=Bronze, 2=Silver, 3=Gold, 4=Platinum, 5=Diamond'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='collected_reward_boxes',
            field=models.IntegerField(default=0, help_text='Number of reward boxes that have been collected/opened'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='reward_history',
            field=models.JSONField(blank=True, default=list, help_text='History of collected rewards with dates and descriptions'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='unlocked_reward_boxes',
            field=models.IntegerField(default=0, help_text='Number of reward boxes unlocked (every 2000 points)'),
        ),
    ]
