# Generated by Django 5.1 on 2026-04-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_badge_and_reward_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(help_text='Badge level (1-10)', unique=True)),
                ('name', models.CharField(help_text='Badge name', max_length=100)),
                ('name_fr', models.CharField(blank=True, help_text='Badge name in French', max_length=100)),
                ('name_en', models.CharField(blank=True, help_text='Badge name in English', max_length=100)),
                ('points_threshold', models.PositiveIntegerField(help_text='Minimum points to achieve this badge')),
                ('color_hex', models.CharField(default='#6b7280', help_text='Primary color (hex)', max_length=7)),
                ('secondary_color_hex', models.CharField(blank=True, help_text='Secondary color (hex)', max_length=7)),
                ('icon_svg', models.TextField(blank=True, help_text='SVG icon path data')),
                ('description', models.TextField(blank=True, help_text='Badge description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this badge is active')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Display order in gallery')),
            ],
            options={
                'verbose_name': 'Badge Configuration',
                'verbose_name_plural': 'Badge Configurations',
                'db_table': 'badge_config',
                'ordering': ['points_threshold'],
            },
        ),
    ]
