# Generated by Django 5.1 on 2026-04-03 17:22

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_badge_config'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Soft deleted'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='badge_level',
            field=models.IntegerField(default=1, help_text='Badge level from BadgeConfig (1=Bronze, 2=Silver, etc.)'),
        ),
        migrations.AddIndex(
            model_name='pointshistory',
            index=models.Index(fields=['member', 'reason', 'created_at'], name='points_hist_member__8f8fb7_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointshistory',
            constraint=models.UniqueConstraint(fields=('member', 'reason', 'points'), name='unique_points_history_entry', violation_error_message='Duplicate points entry: This award has already been recorded.'),
        ),
    ]
