# Generated by Django 5.1.7 on 2026-03-29 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_ibtikar_workflow_states'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('IBTIKAR_FORM', 'Formulaire IBTIKAR'), ('PLATFORM_NOTE', 'Note de Plateforme'), ('RECEPTION_FORM', 'Fiche de Réception'), ('QUOTE', 'Devis')], default='IBTIKAR_FORM', max_length=20, verbose_name='Type de modèle')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(help_text='Modèle DOCX avec placeholders (ex: {{FULL_NAME}}, {{PROJECT_TITLE}})', upload_to='document_templates/%Y/%m/', verbose_name='Fichier DOCX')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Service auquel ce modèle est associé', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Modèle de document',
                'verbose_name_plural': 'Modèles de documents',
                'db_table': 'service_templates',
                'ordering': ['-created_at'],
                'unique_together': {('service', 'template_type', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='TemplatePlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(max_length=100, verbose_name='Placeholder')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('example_value', models.CharField(blank=True, max_length=255, verbose_name='Exemple de valeur')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='documents.servicetemplate')),
            ],
            options={
                'db_table': 'template_placeholders',
                'ordering': ['placeholder'],
            },
        ),
    ]
