# Generated by Django 5.1 on 2026-05-24 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_platformcontent_multilingual"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("IBTIKAR_FORM", "Formulaire IBTIKAR"),
                            ("PLATFORM_NOTE", "Note de Plateforme"),
                            ("RECEPTION_FORM", "Fiche de Réception"),
                            ("QUOTE", "Devis"),
                        ],
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("TOP", "Haut du document (sous l'en-tête)"),
                            ("AFTER_REQUESTER", "Après la section demandeur"),
                            ("AFTER_SAMPLES", "Après le tableau des échantillons"),
                            ("BEFORE_FOOTER", "Juste avant le pied de page"),
                            ("BOTTOM", "Bas du document"),
                        ],
                        default="BOTTOM",
                        max_length=20,
                        verbose_name="Position dans le document",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "English"),
                            ("ar", "العربية"),
                        ],
                        default="fr",
                        max_length=10,
                        verbose_name="Langue",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Titre en gras affiché avant le texte",
                        max_length=255,
                        verbose_name="Titre (optionnel)",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Texte injecté dans le document. Lignes vides séparent les paragraphes.",
                        verbose_name="Contenu",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Ordre d'insertion (priorité plus basse = inséré en premier)",
                        verbose_name="Priorité",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide pour appliquer à tous les services",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_blocks",
                        to="core.service",
                        verbose_name="Service",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloc de contenu",
                "verbose_name_plural": "Blocs de contenu",
                "db_table": "document_blocks",
                "ordering": ["template_type", "position", "priority", "pk"],
                "indexes": [
                    models.Index(
                        fields=["template_type", "service", "language", "is_active"],
                        name="document_bl_templat_c6a16b_idx",
                    )
                ],
            },
        ),
    ]
