# Generated by Django 5.1 on 2026-04-06 00:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0039_request_informed_members_alter_request_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EphemeralMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(help_text='The workflow status/phase when this message was sent', max_length=50)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Archived when request moves to next phase')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment (max 5MB)', null=True, upload_to='ephemeral_attachments/%Y/%m/')),
                ('attachment_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_system_message', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ephemeral_messages', to='core.request')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_ephemeral_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['request', 'phase', 'is_archived'], name='messaging_e_request_d70272_idx'), models.Index(fields=['request', 'created_at'], name='messaging_e_request_578056_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_expected', models.CharField(max_length=255)),
                ('status_when_created', models.CharField(max_length=50)),
                ('urgency', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical — Escalated')], default='NORMAL', max_length=20)),
                ('source', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual (Admin)'), ('POKE', 'Poke from Admin')], default='AUTO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_notified_admin', models.BooleanField(default=False)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_reason', models.CharField(blank=True, default='', max_length=100)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.request')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', 'is_active'], name='messaging_r_request_82c9a6_idx'), models.Index(fields=['target_user', 'is_active'], name='messaging_r_target__d03f74_idx'), models.Index(fields=['urgency', 'is_active'], name='messaging_r_urgency_3c856b_idx')],
            },
        ),
    ]
