"""schema initial local (aucune table d authentification)

Revision ID: b2054b6510ef
Revises: 
Create Date: 2026-08-01 01:26:35.102668

Commission MSI — Designed by Prof. Merzoug Mohamed.
Cette migration doit préserver les dossiers existants.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.models.base import UTCDateTime


revision = 'b2054b6510ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('dossier_id', sa.String(length=36), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=80), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)

    op.create_table('backups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('archive_path', sa.String(length=500), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('includes_master_key', sa.Boolean(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conflicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conflict_id', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('sources_json', sa.Text(), nullable=False),
    sa.Column('required_output', sa.String(length=60), nullable=False),
    sa.Column('arbitrated', sa.Boolean(), nullable=False),
    sa.Column('arbitration_note', sa.Text(), nullable=True),
    sa.Column('arbitrated_by', sa.String(length=200), nullable=True),
    sa.Column('arbitrated_at', UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflicts_conflict_id'), ['conflict_id'], unique=True)

    op.create_table('corrections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('field', sa.String(length=80), nullable=False),
    sa.Column('previous_hash', sa.String(length=80), nullable=False),
    sa.Column('new_hash', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evaluator_label', sa.String(length=200), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corrections_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corrections_entity_type'), ['entity_type'], unique=False)

    op.create_table('dossiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('organizer', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('international_scope_declared', sa.Boolean(), nullable=True),
    sa.Column('report_validated_at', UTCDateTime(), nullable=True),
    sa.Column('report_validated_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dossiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dossiers_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_dossiers_sha256'), ['sha256'], unique=False)

    op.create_table('evaluation_criteria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('source_ref', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('piece_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.String(length=300), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('regulations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('document_date', sa.String(length=20), nullable=True),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('authority', sa.String(length=250), nullable=True),
    sa.Column('effective_from', sa.String(length=20), nullable=True),
    sa.Column('effective_to', sa.String(length=20), nullable=True),
    sa.Column('scope', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('encrypted_path', sa.String(length=500), nullable=True),
    sa.Column('original_name', sa.String(length=300), nullable=True),
    sa.Column('validated_by', sa.String(length=200), nullable=True),
    sa.Column('validated_at', UTCDateTime(), nullable=True),
    sa.Column('integrity_ok', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulations_reference'), ['reference'], unique=False)

    op.create_table('requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('source_id', sa.String(length=60), nullable=False),
    sa.Column('pages_json', sa.Text(), nullable=False),
    sa.Column('source_status', sa.String(length=60), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('translation_status', sa.String(length=30), nullable=False),
    sa.Column('conflict_id', sa.String(length=40), nullable=True),
    sa.Column('implementation', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('test_ids_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_conflict_id'), ['conflict_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_requirement_id'), ['requirement_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_requirements_source_id'), ['source_id'], unique=False)

    op.create_table('rule_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_code', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('recorded_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_versions_rule_code'), ['rule_code'], unique=False)

    op.create_table('source_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=60), nullable=False),
    sa.Column('file_name', sa.String(length=400), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('fmt', sa.String(length=30), nullable=False),
    sa.Column('pages_rendered', sa.Integer(), nullable=False),
    sa.Column('document_date', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('authority', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('present_locally', sa.Boolean(), nullable=False),
    sa.Column('integrity_ok', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_documents_source_id'), ['source_id'], unique=True)

    op.create_table('administrative_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('check_key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('explanation_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('comparison_json', sa.Text(), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('requires_human_confirmation', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id', 'check_key', name='uq_admin_dossier_key')
    )
    with op.batch_alter_table('administrative_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_administrative_checks_dossier_id'), ['dossier_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=False),
    sa.Column('encrypted_path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_sha256'), ['sha256'], unique=False)

    op.create_table('evaluation_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('criterion_key', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('justification_cipher', sa.LargeBinary(), nullable=False),
    sa.Column('source_pages_json', sa.Text(), nullable=False),
    sa.Column('entered_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id', 'criterion_key', name='uq_evaluation_dossier_criterion')
    )
    with op.batch_alter_table('evaluation_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_entries_dossier_id'), ['dossier_id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('rule_code', sa.String(length=60), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('trigger_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('context_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('bbox_json', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('recommended_check', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.String(length=400), nullable=True),
    sa.Column('relation_kind', sa.String(length=40), nullable=True),
    sa.Column('human_status', sa.String(length=25), nullable=False),
    sa.Column('human_comment_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('detection_signature', sa.String(length=64), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_detection_signature'), ['detection_signature'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_rule_code'), ['rule_code'], unique=False)

    op.create_table('institutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('name_cipher', sa.LargeBinary(), nullable=False),
    sa.Column('normalized_key', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institutions_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutions_normalized_key'), ['normalized_key'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('body_cipher', sa.LargeBinary(), nullable=False),
    sa.Column('conclusion', sa.String(length=60), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('author_label', sa.String(length=200), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_dossier_id'), ['dossier_id'], unique=False)

    op.create_table('persons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('display_name_cipher', sa.LargeBinary(), nullable=False),
    sa.Column('normalized_key', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('declared_nationality', sa.String(length=120), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persons_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_normalized_key'), ['normalized_key'], unique=False)

    op.create_table('piece_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('piece_key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('detected_page_no', sa.Integer(), nullable=True),
    sa.Column('detection_excerpt_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('comment_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id', 'piece_key', name='uq_piece_dossier_key')
    )
    with op.batch_alter_table('piece_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_piece_checks_dossier_id'), ['dossier_id'], unique=False)

    op.create_table('regulation_passages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('regulation_id', sa.String(length=36), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('passage_cipher', sa.LargeBinary(), nullable=False),
    sa.Column('translation_status', sa.String(length=30), nullable=False),
    sa.Column('requirement_id', sa.String(length=30), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regulation_passages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulation_passages_regulation_id'), ['regulation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_regulation_passages_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('fmt', sa.String(length=10), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('evaluator_label', sa.String(length=200), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_dossier_id'), ['dossier_id'], unique=False)

    op.create_table('rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('terms_json', sa.Text(), nullable=False),
    sa.Column('context_terms_json', sa.Text(), nullable=False),
    sa.Column('secondary_terms_json', sa.Text(), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.String(length=400), nullable=False),
    sa.Column('source_date', sa.String(length=20), nullable=True),
    sa.Column('authority', sa.String(length=200), nullable=True),
    sa.Column('scope', sa.String(length=200), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('validated_at', UTCDateTime(), nullable=True),
    sa.Column('validated_by', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('suspended_reason', sa.Text(), nullable=True),
    sa.Column('regulation_id', sa.String(length=36), nullable=True),
    sa.Column('is_normative', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_code'), ['code'], unique=True)

    op.create_table('web_research_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scope_note', sa.Text(), nullable=False),
    sa.Column('connectivity_ok', sa.Boolean(), nullable=True),
    sa.Column('providers_json', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('approved_at', UTCDateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('dismissal_justification', sa.Text(), nullable=True),
    sa.Column('started_at', UTCDateTime(), nullable=True),
    sa.Column('finished_at', UTCDateTime(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_research_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_research_runs_dossier_id'), ['dossier_id'], unique=False)

    op.create_table('affiliations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('affiliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliations_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliations_person_id'), ['person_id'], unique=False)

    op.create_table('agent_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=60), nullable=False),
    sa.Column('agent_version', sa.String(length=30), nullable=False),
    sa.Column('subject_label', sa.String(length=400), nullable=False),
    sa.Column('axis_key', sa.String(length=80), nullable=True),
    sa.Column('proposed_score', sa.Float(), nullable=True),
    sa.Column('uncertainty_low', sa.Float(), nullable=True),
    sa.Column('uncertainty_high', sa.Float(), nullable=True),
    sa.Column('evidence_sufficient', sa.Boolean(), nullable=False),
    sa.Column('rationale_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('claim_ids_json', sa.Text(), nullable=False),
    sa.Column('source_ids_json', sa.Text(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['web_research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_assessments_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_assessments_axis_key'), ['axis_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_assessments_run_id'), ['run_id'], unique=False)

    op.create_table('agent_disagreements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('subject_label', sa.String(length=400), nullable=False),
    sa.Column('axis_key', sa.String(length=80), nullable=True),
    sa.Column('agents_json', sa.Text(), nullable=False),
    sa.Column('dispersion', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['web_research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_disagreements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_disagreements_run_id'), ['run_id'], unique=False)

    op.create_table('event_rankings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=False),
    sa.Column('agreement_level', sa.Float(), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('agents_versions_json', sa.Text(), nullable=False),
    sa.Column('thresholds_json', sa.Text(), nullable=False),
    sa.Column('comparison_note', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['web_research_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_rankings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_rankings_dossier_id'), ['dossier_id'], unique=False)

    op.create_table('online_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=60), nullable=False),
    sa.Column('subject_label', sa.String(length=400), nullable=False),
    sa.Column('statement_cipher', sa.LargeBinary(), nullable=False),
    sa.Column('nature', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_ids_json', sa.Text(), nullable=False),
    sa.Column('independent_source_count', sa.Integer(), nullable=False),
    sa.Column('algerian_reference_id', sa.String(length=36), nullable=True),
    sa.Column('algerian_passage_id', sa.String(length=36), nullable=True),
    sa.Column('human_status', sa.String(length=40), nullable=False),
    sa.Column('human_comment_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['algerian_passage_id'], ['regulation_passages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['algerian_reference_id'], ['regulations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['web_research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('online_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_online_claims_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_online_claims_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_online_claims_run_id'), ['run_id'], unique=False)

    op.create_table('pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('original_text_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('corrected_text_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('needs_ocr', sa.Boolean(), nullable=False),
    sa.Column('is_blank', sa.Boolean(), nullable=False),
    sa.Column('is_difficult', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of', sa.Integer(), nullable=True),
    sa.Column('text_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('engine_version', sa.String(length=120), nullable=True),
    sa.Column('analyzed_at', UTCDateTime(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_no', name='uq_page_document_no')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_document_id'), ['document_id'], unique=False)

    op.create_table('participations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participations_dossier_id'), ['dossier_id'], unique=False)

    op.create_table('person_web_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('subject_kind', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=400), nullable=False),
    sa.Column('name_variants_json', sa.Text(), nullable=False),
    sa.Column('declared_affiliation', sa.String(length=400), nullable=True),
    sa.Column('verified_affiliations_json', sa.Text(), nullable=False),
    sa.Column('public_identifiers_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('summary_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['web_research_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_web_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_web_profiles_dossier_id'), ['dossier_id'], unique=False)

    op.create_table('web_queries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('subject_kind', sa.String(length=40), nullable=False),
    sa.Column('subject_label', sa.String(length=400), nullable=False),
    sa.Column('query_text', sa.String(length=600), nullable=False),
    sa.Column('purpose', sa.String(length=300), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('sent_at', UTCDateTime(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('redaction_report_json', sa.Text(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['web_research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_queries_run_id'), ['run_id'], unique=False)

    op.create_table('association_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('organization', sa.String(length=400), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('period', sa.String(length=120), nullable=True),
    sa.Column('nature', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('source_ids_json', sa.Text(), nullable=False),
    sa.Column('legal_link_established', sa.Boolean(), nullable=False),
    sa.Column('note_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['person_web_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('association_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_association_links_profile_id'), ['profile_id'], unique=False)

    op.create_table('event_ranking_axes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ranking_id', sa.String(length=36), nullable=False),
    sa.Column('axis_key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('proposed_score', sa.Float(), nullable=True),
    sa.Column('uncertainty_low', sa.Float(), nullable=True),
    sa.Column('uncertainty_high', sa.Float(), nullable=True),
    sa.Column('dispersion', sa.Float(), nullable=True),
    sa.Column('not_provided', sa.Boolean(), nullable=False),
    sa.Column('justification_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('source_ids_json', sa.Text(), nullable=False),
    sa.Column('human_decision', sa.String(length=30), nullable=False),
    sa.Column('human_score', sa.Float(), nullable=True),
    sa.Column('human_justification_cipher', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['ranking_id'], ['event_rankings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_ranking_axes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_ranking_axes_ranking_id'), ['ranking_id'], unique=False)

    op.create_table('extracted_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=250), nullable=False),
    sa.Column('initial_value_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('current_value_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('source_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('bbox_json', sa.Text(), nullable=True),
    sa.Column('extraction_mode', sa.String(length=25), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('reinforced_control', sa.Boolean(), nullable=False),
    sa.Column('manual_entry_validated', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extracted_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_items_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_items_key'), ['key'], unique=False)

    op.create_table('identity_disambiguations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_label', sa.String(length=400), nullable=False),
    sa.Column('candidate_affiliation', sa.String(length=400), nullable=True),
    sa.Column('discriminators_json', sa.Text(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['person_web_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identity_disambiguations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_disambiguations_profile_id'), ['profile_id'], unique=False)

    op.create_table('ocr_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('engine', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=60), nullable=False),
    sa.Column('languages', sa.String(length=60), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('low_confidence_words', sa.Integer(), nullable=False),
    sa.Column('result_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('boxes_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocr_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocr_runs_page_id'), ['page_id'], unique=False)

    op.create_table('web_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('query_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=600), nullable=True),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('published_on', sa.String(length=30), nullable=True),
    sa.Column('consulted_at', UTCDateTime(), nullable=False),
    sa.Column('tier', sa.String(length=40), nullable=False),
    sa.Column('excerpt_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['web_queries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['web_research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_sources_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_sources_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_sources_run_id'))
        batch_op.drop_index(batch_op.f('ix_web_sources_domain'))

    op.drop_table('web_sources')
    with op.batch_alter_table('ocr_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocr_runs_page_id'))

    op.drop_table('ocr_runs')
    with op.batch_alter_table('identity_disambiguations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_disambiguations_profile_id'))

    op.drop_table('identity_disambiguations')
    with op.batch_alter_table('extracted_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_items_key'))
        batch_op.drop_index(batch_op.f('ix_extracted_items_dossier_id'))

    op.drop_table('extracted_items')
    with op.batch_alter_table('event_ranking_axes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_ranking_axes_ranking_id'))

    op.drop_table('event_ranking_axes')
    with op.batch_alter_table('association_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_association_links_profile_id'))

    op.drop_table('association_links')
    with op.batch_alter_table('web_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_queries_run_id'))

    op.drop_table('web_queries')
    with op.batch_alter_table('person_web_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_web_profiles_dossier_id'))

    op.drop_table('person_web_profiles')
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participations_dossier_id'))

    op.drop_table('participations')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_document_id'))

    op.drop_table('pages')
    with op.batch_alter_table('online_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_online_claims_run_id'))
        batch_op.drop_index(batch_op.f('ix_online_claims_dossier_id'))
        batch_op.drop_index(batch_op.f('ix_online_claims_agent_name'))

    op.drop_table('online_claims')
    with op.batch_alter_table('event_rankings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_rankings_dossier_id'))

    op.drop_table('event_rankings')
    with op.batch_alter_table('agent_disagreements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_disagreements_run_id'))

    op.drop_table('agent_disagreements')
    with op.batch_alter_table('agent_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_assessments_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_assessments_axis_key'))
        batch_op.drop_index(batch_op.f('ix_agent_assessments_agent_name'))

    op.drop_table('agent_assessments')
    with op.batch_alter_table('affiliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliations_person_id'))
        batch_op.drop_index(batch_op.f('ix_affiliations_institution_id'))

    op.drop_table('affiliations')
    with op.batch_alter_table('web_research_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_research_runs_dossier_id'))

    op.drop_table('web_research_runs')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_code'))

    op.drop_table('rules')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_dossier_id'))

    op.drop_table('reports')
    with op.batch_alter_table('regulation_passages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulation_passages_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_regulation_passages_regulation_id'))

    op.drop_table('regulation_passages')
    with op.batch_alter_table('piece_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_piece_checks_dossier_id'))

    op.drop_table('piece_checks')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persons_normalized_key'))
        batch_op.drop_index(batch_op.f('ix_persons_dossier_id'))

    op.drop_table('persons')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_dossier_id'))

    op.drop_table('notes')
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_normalized_key'))
        batch_op.drop_index(batch_op.f('ix_institutions_dossier_id'))

    op.drop_table('institutions')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_rule_code'))
        batch_op.drop_index(batch_op.f('ix_findings_dossier_id'))
        batch_op.drop_index(batch_op.f('ix_findings_detection_signature'))
        batch_op.drop_index(batch_op.f('ix_findings_category'))

    op.drop_table('findings')
    with op.batch_alter_table('evaluation_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_entries_dossier_id'))

    op.drop_table('evaluation_entries')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_documents_dossier_id'))

    op.drop_table('documents')
    with op.batch_alter_table('administrative_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_administrative_checks_dossier_id'))

    op.drop_table('administrative_checks')
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_documents_source_id'))

    op.drop_table('source_documents')
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_versions_rule_code'))

    op.drop_table('rule_versions')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_source_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_conflict_id'))

    op.drop_table('requirements')
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulations_reference'))

    op.drop_table('regulations')
    op.drop_table('piece_definitions')
    op.drop_table('evaluation_criteria')
    with op.batch_alter_table('dossiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dossiers_sha256'))
        batch_op.drop_index(batch_op.f('ix_dossiers_reference'))

    op.drop_table('dossiers')
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corrections_entity_type'))
        batch_op.drop_index(batch_op.f('ix_corrections_entity_id'))

    op.drop_table('corrections')
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflicts_conflict_id'))

    op.drop_table('conflicts')
    op.drop_table('backups')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_dossier_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
