"""analyse automatique V4 preuves criteres score avis jobs

Revision ID: db829f2182b2
Revises: b2054b6510ef
Create Date: 2026-08-01 11:16:31.313022

Commission MSI — Designed by Prof. Merzoug Mohamed.
Cette migration doit préserver les dossiers existants.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.models.base import UTCDateTime


revision = 'db829f2182b2'
down_revision = 'b2054b6510ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('model_id', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('input_sha256', sa.String(length=64), nullable=True),
    sa.Column('output_sha256', sa.String(length=64), nullable=True),
    sa.Column('data_categories', sa.Text(), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_calls_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_calls_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_calls_status'), ['status'], unique=False)

    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('step_label', sa.String(length=200), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('pages_total', sa.Integer(), nullable=False),
    sa.Column('pages_done', sa.Integer(), nullable=False),
    sa.Column('searches_done', sa.Integer(), nullable=False),
    sa.Column('validations_done', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=80), nullable=True),
    sa.Column('lease_expires_at', UTCDateTime(), nullable=True),
    sa.Column('heartbeat_at', UTCDateTime(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('analysis_mode', sa.String(length=20), nullable=False),
    sa.Column('model_id', sa.String(length=120), nullable=True),
    sa.Column('referential_version', sa.String(length=20), nullable=True),
    sa.Column('grid_version', sa.String(length=20), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('started_at', UTCDateTime(), nullable=True),
    sa.Column('finished_at', UTCDateTime(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_jobs_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_source_sha256'), ['source_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_state'), ['state'], unique=False)

    op.create_table('audit_disagreements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=60), nullable=False),
    sa.Column('criterion_code', sa.String(length=10), nullable=True),
    sa.Column('analyst_value', sa.Text(), nullable=False),
    sa.Column('auditor_value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('evidence_refs', sa.Text(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_disagreements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_disagreements_criterion_code'), ['criterion_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_disagreements_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_disagreements_job_id'), ['job_id'], unique=False)

    op.create_table('criterion_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('family', sa.String(length=30), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=3), nullable=False),
    sa.Column('finding_cipher', sa.LargeBinary(), nullable=False),
    sa.Column('exact_source', sa.String(length=400), nullable=False),
    sa.Column('source_page', sa.String(length=40), nullable=False),
    sa.Column('nature', sa.String(length=20), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('evidence_refs', sa.Text(), nullable=False),
    sa.Column('calculation_json', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('referential_version', sa.String(length=20), nullable=False),
    sa.Column('human_status', sa.String(length=3), nullable=True),
    sa.Column('human_comment_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id', 'code', name='uq_criterion_per_dossier')
    )
    with op.batch_alter_table('criterion_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_criterion_results_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_criterion_results_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_criterion_results_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_criterion_results_status'), ['status'], unique=False)

    op.create_table('evidence_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('locator', sa.String(length=300), nullable=True),
    sa.Column('excerpt_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id', 'reference', name='uq_evidence_reference')
    )
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_items_content_sha256'), ['content_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_reference'), ['reference'], unique=False)

    op.create_table('proposed_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('avis', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('motivation', sa.Text(), nullable=False),
    sa.Column('triggered_rules_json', sa.Text(), nullable=False),
    sa.Column('blocking_criteria', sa.Text(), nullable=False),
    sa.Column('reserves_json', sa.Text(), nullable=False),
    sa.Column('complements_json', sa.Text(), nullable=False),
    sa.Column('scientific_total', sa.Integer(), nullable=True),
    sa.Column('referential_version', sa.String(length=20), nullable=False),
    sa.Column('human_decision', sa.String(length=60), nullable=True),
    sa.Column('human_motivation_cipher', sa.LargeBinary(), nullable=True),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.Column('decided_at', UTCDateTime(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposed_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposed_decisions_avis'), ['avis'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposed_decisions_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposed_decisions_job_id'), ['job_id'], unique=False)

    op.create_table('report_qa_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('checks_json', sa.Text(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('docx_sha256', sa.String(length=64), nullable=True),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_qa_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_qa_results_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_qa_results_job_id'), ['job_id'], unique=False)

    op.create_table('scientific_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('maximum', sa.Integer(), nullable=False),
    sa.Column('grid_version', sa.String(length=20), nullable=False),
    sa.Column('validated_total', sa.Integer(), nullable=True),
    sa.Column('validated_by', sa.String(length=200), nullable=True),
    sa.Column('validated_at', UTCDateTime(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scientific_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scientific_scores_dossier_id'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scientific_scores_job_id'), ['job_id'], unique=False)

    op.create_table('analysis_checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('step', sa.String(length=30), nullable=False),
    sa.Column('input_sha256', sa.String(length=64), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'step', name='uq_checkpoint_step')
    )
    with op.batch_alter_table('analysis_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_checkpoints_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_checkpoints_step'), ['step'], unique=False)

    op.create_table('scientific_subscores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('score_id', sa.String(length=36), nullable=False),
    sa.Column('family_key', sa.String(length=60), nullable=False),
    sa.Column('family_label', sa.String(length=200), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('maximum', sa.Integer(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('evidence_refs', sa.Text(), nullable=False),
    sa.Column('human_score', sa.Integer(), nullable=True),
    sa.Column('human_justification', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['score_id'], ['scientific_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scientific_subscores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scientific_subscores_score_id'), ['score_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scientific_subscores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scientific_subscores_score_id'))

    op.drop_table('scientific_subscores')
    with op.batch_alter_table('analysis_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_checkpoints_step'))
        batch_op.drop_index(batch_op.f('ix_analysis_checkpoints_job_id'))

    op.drop_table('analysis_checkpoints')
    with op.batch_alter_table('scientific_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scientific_scores_job_id'))
        batch_op.drop_index(batch_op.f('ix_scientific_scores_dossier_id'))

    op.drop_table('scientific_scores')
    with op.batch_alter_table('report_qa_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_qa_results_job_id'))
        batch_op.drop_index(batch_op.f('ix_report_qa_results_dossier_id'))

    op.drop_table('report_qa_results')
    with op.batch_alter_table('proposed_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposed_decisions_job_id'))
        batch_op.drop_index(batch_op.f('ix_proposed_decisions_dossier_id'))
        batch_op.drop_index(batch_op.f('ix_proposed_decisions_avis'))

    op.drop_table('proposed_decisions')
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_items_reference'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_kind'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_dossier_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_content_sha256'))

    op.drop_table('evidence_items')
    with op.batch_alter_table('criterion_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_criterion_results_status'))
        batch_op.drop_index(batch_op.f('ix_criterion_results_job_id'))
        batch_op.drop_index(batch_op.f('ix_criterion_results_dossier_id'))
        batch_op.drop_index(batch_op.f('ix_criterion_results_code'))

    op.drop_table('criterion_results')
    with op.batch_alter_table('audit_disagreements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_disagreements_job_id'))
        batch_op.drop_index(batch_op.f('ix_audit_disagreements_dossier_id'))
        batch_op.drop_index(batch_op.f('ix_audit_disagreements_criterion_code'))

    op.drop_table('audit_disagreements')
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_state'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_source_sha256'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_dossier_id'))

    op.drop_table('analysis_jobs')
    with op.batch_alter_table('ai_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_calls_status'))
        batch_op.drop_index(batch_op.f('ix_ai_calls_job_id'))
        batch_op.drop_index(batch_op.f('ix_ai_calls_dossier_id'))

    op.drop_table('ai_calls')
    # ### end Alembic commands ###
