# Generated by Django 5.1.7 on 2026-03-29 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_service_pricing'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, help_text='Action button text', max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='Action URL (e.g., accept, reject)', max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='link_text',
            field=models.CharField(blank=True, help_text='Text for the link', max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='link_url',
            field=models.CharField(blank=True, help_text='URL for deep linking', max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Info'), ('WORKFLOW', 'Workflow'), ('SYSTEM', 'System'), ('ASSIGNMENT', 'Assignment'), ('STATUS_CHANGE', 'Status Change'), ('APPOINTMENT', 'Appointment'), ('REPORT', 'Report Ready'), ('PAYMENT', 'Payment')], default='INFO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
    ]
