# Generated by Django 5.1 on 2026-05-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_add_notification_deep_linking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("INFO", "Info"),
                    ("WORKFLOW", "Workflow"),
                    ("SYSTEM", "System"),
                    ("ASSIGNMENT", "Assignment"),
                    ("STATUS_CHANGE", "Status Change"),
                    ("APPOINTMENT", "Appointment"),
                    ("REPORT", "Report Ready"),
                    ("PAYMENT", "Payment"),
                    ("REWARD", "Reward"),
                ],
                default="INFO",
                max_length=20,
            ),
        ),
    ]
