# Generated by Django 5.1 on 2026-04-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Info'), ('WORKFLOW', 'Workflow'), ('SYSTEM', 'System'), ('ASSIGNMENT', 'Assignment'), ('STATUS_CHANGE', 'Status Change'), ('APPOINTMENT', 'Appointment'), ('REPORT', 'Report Ready'), ('PAYMENT', 'Payment'), ('DOCUMENT_READY', 'Document Ready'), ('REWARD', 'Reward/Gift'), ('POINTS', 'Points'), ('MESSAGE', 'Message'), ('REMINDER', 'Reminder'), ('REMINDER_ESCALATION', 'Reminder Escalation'), ('OBSERVER', 'Observer Notification'), ('POKE', 'Admin Poke')], default='INFO', max_length=20),
        ),
    ]
